# Generated by Django 5.2 on 2025-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_url', models.URLField(default='https://grupochegou.atlassian.net/', help_text='URL base da instância Jira Cloud', verbose_name='URL do Jira')),
                ('jira_email', models.EmailField(default='viniciuschegouoperacional@gmail.com', help_text='Email do usuário Jira', max_length=254, verbose_name='Email do Jira')),
                ('jira_project_key', models.CharField(default='CHEGOU', help_text='Chave do projeto Jira (ex: CHEGOU)', max_length=50, verbose_name='Chave do Projeto')),
                ('api_token_encrypted', models.TextField(help_text='Token da API Jira armazenado de forma segura', verbose_name='API Token Criptografado')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa', verbose_name='Ativo')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração Jira',
                'verbose_name_plural': 'Configurações Jira',
                'ordering': ['-criado_em'],
            },
        ),
    ]
