# backend/config/settings.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
from urllib.parse import urlparse

# Opção para forçar uso de SQLite (para depuração/testes)
FORCE_SQLITE = os.getenv('FORCE_SQLITE', 'False') == 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Carregar variáveis de ambiente do .env ---
# Útil para desenvolvimento LOCAL. No Railway, use as variáveis de ambiente da plataforma.
load_dotenv(os.path.join(BASE_DIR, '.env'))
# --- Fim do carregamento do .env ---

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# <<< LER DO AMBIENTE, padrão é False (produção) >>>
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# --- Configuração ALLOWED_HOSTS para produção ---
ALLOWED_HOSTS_STRING = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = []
if ALLOWED_HOSTS_STRING:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_STRING.split(','))

# Adiciona a URL pública que o Railway dá para seu app (se disponível em env)
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
if RAILWAY_STATIC_URL and '/' in RAILWAY_STATIC_URL:
    RAILWAY_HOSTNAME = RAILWAY_STATIC_URL.split('/')[0]
    if RAILWAY_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RAILWAY_HOSTNAME)

# Adiciona localhost e 127.0.0.1 se estiver em modo DEBUG para testes locais
if DEBUG:
    ALLOWED_HOSTS.append('localhost')
    ALLOWED_HOSTS.append('127.0.0.1')
    if not SECRET_KEY:
       SECRET_KEY = 'django-insecure-fallback-key-change-this-in-real-env-or-prod'
       print("\n\nAVISO: Usando SECRET_KEY de fallback para DEBUG. Defina DJANGO_SECRET_KEY no .env\n\n")
elif not SECRET_KEY:
    # Em produção (não DEBUG), SECRET_KEY É OBRIGATÓRIA
    raise ValueError("ERRO CRÍTICO: DJANGO_SECRET_KEY não definida no ambiente de produção!")
# --- Fim ALLOWED_HOSTS ---

# --- Chave da API OpenAI ---
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
if not OPENAI_API_KEY and DEBUG:
    print("AVISO: OPENAI_API_KEY não está definida no arquivo .env!")
# --- Fim da chave OpenAI ---

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application' # Mantido para compatibilidade
ASGI_APPLICATION = 'config.asgi.application'

# --- NOVA CONFIGURAÇÃO DO BANCO DE DADOS ---

# Se forçar SQLite, usa SQLite independente de outras configurações
if FORCE_SQLITE:
    print("AVISO: Usando SQLite por configuração forçada (FORCE_SQLITE=True).")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Configuração normal com PostgreSQL
    DATABASE_URL_INTERNAL = os.getenv('DATABASE_URL')
    DATABASE_URL_PUBLIC = os.getenv('DATABASE_PUBLIC_URL')

    DATABASES = {}

    # Tenta usar URL pública com dj_database_url em vez de parsing manual
    if DATABASE_URL_PUBLIC:
        print("INFO: Configurando banco de dados usando URL PÚBLICA com dj_database_url")
        try:
            DATABASES = {
                'default': dj_database_url.config(
                    default=DATABASE_URL_PUBLIC,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=False  # Desabilitado temporariamente para diagnóstico
                )
            }
            print("INFO: Configuração com URL pública parece bem-sucedida")
        except Exception as e:
            print(f"ERRO: Falha ao configurar com DATABASE_PUBLIC_URL via dj_database_url: {e}")
            
            # Tenta método antigo (parsing manual) como fallback
            try:
                print("INFO: Tentando método alternativo com URL pública (parse manual)")
                url = urlparse(DATABASE_URL_PUBLIC)
                DATABASES['default'] = {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': url.path[1:],
                    'USER': url.username,
                    'PASSWORD': url.password,
                    'HOST': url.hostname,
                    'PORT': url.port,
                    'OPTIONS': {'sslmode': 'prefer'}  # mudado de 'require' para 'prefer'
                }
            except Exception as e2:
                print(f"ERRO: Fallback também falhou ao parsear DATABASE_PUBLIC_URL: {e2}")

    # Se não configurou com URL pública, tenta URL interna
    if not DATABASES and DATABASE_URL_INTERNAL:
        print("INFO: Configurando banco de dados usando URL INTERNA")
        try:
            DATABASES = {
                'default': dj_database_url.config(
                    default=DATABASE_URL_INTERNAL,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=False  # Desabilitado temporariamente para diagnóstico
                )
            }
        except Exception as e:
            print(f"ERRO: Falha ao configurar com DATABASE_URL interna: {e}")

    # Fallback final para SQLite se tudo mais falhar
    if not DATABASES:
        print("AVISO: Nenhuma URL de banco de dados válida configurada. Usando SQLite local.")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# --- CÓDIGO DE DIAGNÓSTICO DO BANCO DE DADOS ---
if DATABASES and 'default' in DATABASES:
    print("=== DIAGNÓSTICO DE BANCO DE DADOS ===")
    db_info = DATABASES['default'].copy()
    if 'PASSWORD' in db_info:
        db_info['PASSWORD'] = '********'  # Esconder senha nos logs
    print(f"ENGINE: {db_info.get('ENGINE')}")
    print(f"NAME: {db_info.get('NAME')}")
    print(f"USER: {db_info.get('USER')}")
    print(f"HOST: {db_info.get('HOST')}")
    print(f"PORT: {db_info.get('PORT')}")
    print(f"OPTIONS: {db_info.get('OPTIONS', {})}")
    
    # Teste de conexão (apenas em produção)
    if not DEBUG:
        try:
            print("Tentando conexão de teste com o banco...")
            # Importações dentro do bloco try para evitar erros
            import django.db
            from django.db import connection
            connection.ensure_connection()
            print("Conexão de teste BEM-SUCEDIDA!")
        except Exception as e:
            print(f"ERRO NA CONEXÃO DE TESTE: {type(e).__name__}: {str(e)}")
            
            # Tenta diagnóstico mais detalhado com psycopg2 diretamente
            try:
                import psycopg2
                db_config = DATABASES['default']
                if db_config['ENGINE'] == 'django.db.backends.postgresql':
                    print("Tentando conexão direta com psycopg2...")
                    psycopg2.connect(
                        dbname=db_config.get('NAME', ''),
                        user=db_config.get('USER', ''),
                        password=db_config.get('PASSWORD', ''),
                        host=db_config.get('HOST', ''),
                        port=db_config.get('PORT', ''),
                    )
                    print("Conexão psycopg2 direta BEM-SUCEDIDA!")
            except Exception as psycopg2_err:
                print(f"ERRO NA CONEXÃO PSYCOPG2: {type(psycopg2_err).__name__}: {str(psycopg2_err)}")

    print("=== FIM DO DIAGNÓSTICO ===")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# --- Configurações de Estáticos para Produção com Whitenoise ---
STATIC_ROOT = BASE_DIR / 'staticfiles'

# <<< Storage OBRIGATÓRIO para Whitenoise (Django >= 4.2) >>>
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_DIRS = [
    BASE_DIR / 'static_files',
]

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuração do CORS ---
# <<< MODIFICADO para ler origens do ambiente >>>
CORS_ALLOWED_ORIGINS_STRING = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [
    "https://chegouhub.up.railway.app",
    "https://chegou-hubb-production.up.railway.app",
    "https://www.chegouhub.up.railway.app",
    "http://chegouhub.up.railway.app",  # Para ambientes de desenvolvimento
]
if DEBUG:
    # Permitir localhost em DEBUG
    CORS_ALLOWED_ORIGINS.extend([
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ])
if CORS_ALLOWED_ORIGINS_STRING:
    # Adiciona URLs do ambiente
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CORS_ALLOWED_ORIGINS_STRING.split(',')])

# Atualize CSRF_TRUSTED_ORIGINS - deve incluir a mesma lista
CSRF_TRUSTED_ORIGINS = [
    "https://chegouhub.up.railway.app", 
    "https://chegou-hubb-production.up.railway.app",
    "https://www.chegouhub.up.railway.app",
    "http://chegouhub.up.railway.app",  # Para ambientes de desenvolvimento
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ])
# Corrigi para usar CORS_ALLOWED_ORIGINS_STRING já que CSRF_TRUSTED_ORIGINS_STRING não existe
if CORS_ALLOWED_ORIGINS_STRING:
    # Adiciona URLs do ambiente
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in CORS_ALLOWED_ORIGINS_STRING.split(',')])

# Configurações CORS adicionais
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',  # Adicionado
    'pragma',         # Adicionado
]

# Configurações CSRF Cookie ajustadas
CSRF_COOKIE_SECURE = not DEBUG  # True em produção, False em desenvolvimento
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'  # 'None' requer HTTPS em produção
CSRF_COOKIE_HTTPONLY = False  # Precisa ser acessível por JavaScript
CSRF_USE_SESSIONS = False  # Armazenar em cookies é mais simples para APIs
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'  # Corresponde ao axios.defaults.xsrfHeaderName = 'X-CSRFToken'

# <<< Ajustes de Segurança para Produção (HTTPS) >>>
if not DEBUG: # Em produção
    CSRF_COOKIE_SECURE = True   # OBRIGATÓRIO para SameSite=None
    CSRF_COOKIE_SAMESITE = 'None' # Permite envio cross-site (diferentes subdomínios)
else: # Em desenvolvimento (DEBUG=True)
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax' 

# Configuração de domínio para cookies CSRF (NOVA CONFIGURAÇÃO)
CSRF_COOKIE_DOMAIN = '.railway.app'  # Permite compartilhar cookies entre subdomínios

# --- Configuração REST Framework (sem mudanças) ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}
# --- Fim REST Framework ---

# <<< Logging (Aumentado para DEBUG para mais informações) >>>
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # Alterado para DEBUG para mais detalhes
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Alterado para DEBUG para mais detalhes
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Ativar logs específicos de conexão do banco
            'propagate': False,
        },
    },
}