# backend/config/settings.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Carregar variáveis de ambiente do .env ---
# Útil para desenvolvimento LOCAL. No Railway, use as variáveis de ambiente da plataforma.
load_dotenv(os.path.join(BASE_DIR, '.env'))
# --- Fim do carregamento do .env ---

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# <<< LER DO AMBIENTE, padrão é False (produção) >>>
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# --- Configuração ALLOWED_HOSTS para produção ---
ALLOWED_HOSTS = [
    'chegou-hubb-production.up.railway.app',
    'chegouhub.up.railway.app',
    'railway.app',
    '.railway.app',
    'localhost',
    '127.0.0.1',
]

# Adicionar qualquer host adicional fornecido na variável de ambiente
ALLOWED_HOSTS_STRING = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_STRING:
    ALLOWED_HOSTS.extend([host.strip() for host in ALLOWED_HOSTS_STRING.split(',')])

# Adicionar automaticamente o hostname do Railway
RAILWAY_STATIC_URL = os.getenv('RAILWAY_STATIC_URL')
if RAILWAY_STATIC_URL and '/' in RAILWAY_STATIC_URL:
    RAILWAY_HOSTNAME = RAILWAY_STATIC_URL.split('/')[0]
    if RAILWAY_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RAILWAY_HOSTNAME)

# Adicionar automaticamente hostname do DATABASE_PUBLIC_URL
DATABASE_PUBLIC_URL = os.getenv('DATABASE_PUBLIC_URL', '')
if DATABASE_PUBLIC_URL and '@' in DATABASE_PUBLIC_URL:
    DB_HOSTNAME = DATABASE_PUBLIC_URL.split('@')[1].split(':')[0]
    if DB_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(DB_HOSTNAME)

if not SECRET_KEY and not DEBUG:
    # Em produção (não DEBUG), SECRET_KEY É OBRIGATÓRIA
    raise ValueError("ERRO CRÍTICO: DJANGO_SECRET_KEY não definida no ambiente de produção!")
# --- Fim ALLOWED_HOSTS ---

# --- Chave da API OpenAI ---
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
if not OPENAI_API_KEY and DEBUG:
    print("AVISO: OPENAI_API_KEY não está definida no arquivo .env!")
# --- Fim da chave OpenAI ---

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core.apps.CoreConfig',
]

# *** CORREÇÃO DE ORDEM DE MIDDLEWARES PARA CORS ***
MIDDLEWARE = [
    'core.middleware.CustomCorsMiddleware'
    'corsheaders.middleware.CorsMiddleware',  # DEVE vir antes do SecurityMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]     

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application' # Mantido para compatibilidade
ASGI_APPLICATION = 'config.asgi.application'

# --- DIAGNÓSTICO DO AMBIENTE ---
print("=== DIAGNÓSTICO DE AMBIENTE ===")
print(f"DATABASE_URL: {'Definido' if os.getenv('DATABASE_URL') else 'NÃO DEFINIDO'}")
print(f"DATABASE_PUBLIC_URL: {'Definido' if os.getenv('DATABASE_PUBLIC_URL') else 'NÃO DEFINIDO'}")
print(f"DEBUG: {os.getenv('DEBUG', 'False')}")
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print("=== FIM DIAGNÓSTICO DE AMBIENTE ===")

# --- Configuração Otimizada para PostgreSQL no Railway ---
DATABASE_URL = os.getenv('DATABASE_URL')
DATABASE_PUBLIC_URL = os.getenv('DATABASE_PUBLIC_URL')

# Usar DATABASE_PUBLIC_URL se DATABASE_URL não estiver disponível
if not DATABASE_URL and DATABASE_PUBLIC_URL:
    print("AVISO: DATABASE_URL não encontrada, usando DATABASE_PUBLIC_URL.")
    DATABASE_URL = DATABASE_PUBLIC_URL

if not DATABASE_URL:
    raise ValueError("ERRO CRÍTICO: DATABASE_URL ou DATABASE_PUBLIC_URL não definida no ambiente. PostgreSQL é obrigatório para este aplicativo.")

# Configuração com dj-database-url
DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=False  # Desabilitado para diagnóstico
    )
}

# Log da configuração (sem expor dados sensíveis)
print("=== CONFIGURAÇÃO DO BANCO DE DADOS ===")
db_info = DATABASES['default'].copy()
if 'PASSWORD' in db_info:
    db_info['PASSWORD'] = '********'
print(f"ENGINE: {db_info.get('ENGINE')}")
print(f"NAME: {db_info.get('NAME')}")
print(f"USER: {db_info.get('USER')}")
print(f"HOST: {db_info.get('HOST')}")
print(f"PORT: {db_info.get('PORT')}")
print("=== FIM CONFIGURAÇÃO DO BANCO DE DADOS ===")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# --- Configurações de Estáticos para Produção com Whitenoise ---
STATIC_ROOT = BASE_DIR / 'staticfiles'

# <<< Storage OBRIGATÓRIO para Whitenoise (Django >= 4.2) >>>
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_DIRS = [
    BASE_DIR / 'static_files',
]

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === INÍCIO DA CONFIGURAÇÃO PARA RESOLVER CORS CROSS-DOMAIN ===

# Permitir TODAS as origens (necessário para multi-domínio Railway sem proxy)
CORS_ALLOW_ALL_ORIGINS = True

# Permitir credenciais nas requisições CORS
CORS_ALLOW_CREDENTIALS = True

# Expor cabeçalhos necessários
CORS_EXPOSE_HEADERS = [
    'Content-Type', 
    'X-CSRFToken',
    'Set-Cookie',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Credentials',
]

# Permitir todos os métodos HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Permitir todos os cabeçalhos nas requisições
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
]

# Aumentar o tempo de cache do preflight OPTIONS
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 horas

# --- Configuração CSRF para multi-domínio ---
CSRF_TRUSTED_ORIGINS = [
    "https://chegouhub.up.railway.app",
    "https://chegou-hubb-production.up.railway.app",
    "https://www.chegouhub.up.railway.app",
    "http://chegouhub.up.railway.app",
    "http://chegou-hubb-production.up.railway.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Desabilitar configurações que podem interferir com cross-domain
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = None  # Permitir uso cross-site
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

# === FIM DA CONFIGURAÇÃO PARA RESOLVER CORS CROSS-DOMAIN ===

# --- Configuração REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# <<< Logging para mais detalhes >>>
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'corsheaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}