[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate && mkdir -p staticfiles/media && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level info --timeout 1800 --keep-alive 300 --max-requests 0 --workers 2'
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
CI = "false"
DISABLE_ESLINT_PLUGIN = "true"
GENERATE_SOURCEMAP = "false"