# Generated by Django 5.2 on 2025-06-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engajamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('engajamento_id', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Like', 'Like'), ('Amei', 'Amei'), ('Uau', 'Uau')], max_length=10)),
                ('funcionando', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engajamento',
                'verbose_name_plural': 'Engajamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('ordem_api', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('engajamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engajamento.engajamento')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoEngajamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(help_text='URLs separadas por linha')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('resultado_api', models.JSONField(blank=True, default=dict)),
                ('total_links', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('engajamentos', models.ManyToManyField(through='engajamento.ItemPedido', to='engajamento.engajamento')),
            ],
            options={
                'verbose_name': 'Pedido de Engajamento',
                'verbose_name_plural': 'Pedidos de Engajamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engajamento.pedidoengajamento'),
        ),
    ]
