# Generated by Django 5.2 on 2025-08-29 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processamento', '0008_resolvedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(blank=True, help_text='ID do produto no Shopify', null=True)),
                ('shopify_variant_id', models.BigIntegerField(blank=True, help_text='ID da variação no Shopify', null=True)),
                ('sku', models.CharField(help_text='SKU único do produto', max_length=100)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('estoque_inicial', models.IntegerField(default=0, verbose_name='Estoque inicial')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque atual')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque mínimo')),
                ('estoque_maximo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Estoque máximo')),
                ('alerta_estoque_baixo', models.BooleanField(default=True, verbose_name='Alertar estoque baixo')),
                ('alerta_estoque_zero', models.BooleanField(default=True, verbose_name='Alertar estoque zerado')),
                ('sync_shopify_enabled', models.BooleanField(default=True, verbose_name='Sincronizar com Shopify')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('erro_sincronizacao', models.TextField(blank=True, verbose_name='Erro na sincronização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto ativo')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo unitário')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de venda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('loja_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.shopifyconfig', verbose_name='Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produto em Estoque',
                'verbose_name_plural': 'Produtos em Estoque',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('perda', 'Perda'), ('transferencia', 'Transferência'), ('sync_shopify', 'Sincronização Shopify')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('estoque_anterior', models.IntegerField(verbose_name='Estoque anterior')),
                ('estoque_posterior', models.IntegerField(verbose_name='Estoque posterior')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido_shopify_id', models.BigIntegerField(blank=True, help_text='ID do pedido no Shopify', null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total')),
                ('origem_sync', models.CharField(blank=True, help_text='Origem da sincronização (shopify, manual, api)', max_length=50)),
                ('dados_sync', models.JSONField(default=dict, help_text='Dados adicionais da sincronização')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP de origem da operação', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produtoestoque')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('estoque_zero', 'Estoque Zerado'), ('estoque_negativo', 'Estoque Negativo'), ('erro_sync', 'Erro de Sincronização'), ('produto_inativo', 'Produto Inativo'), ('limite_maximo', 'Limite Máximo Atingido'), ('movimentacao_suspeita', 'Movimentação Suspeita')], max_length=25, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('lido', 'Lido'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_contexto', models.JSONField(default=dict, help_text='Dados contextuais do alerta')),
                ('valor_atual', models.IntegerField(help_text='Valor atual que gerou o alerta')),
                ('valor_limite', models.IntegerField(blank=True, help_text='Valor limite configurado', null=True)),
                ('acao_sugerida', models.TextField(blank=True, verbose_name='Ação sugerida')),
                ('pode_resolver_automaticamente', models.BooleanField(default=False, verbose_name='Resolução automática')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('primeira_ocorrencia', models.DateTimeField(auto_now_add=True)),
                ('ultima_ocorrencia', models.DateTimeField(auto_now=True)),
                ('contador_ocorrencias', models.IntegerField(default=1, verbose_name='Número de ocorrências')),
                ('usuario_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estoque.produtoestoque')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'ordering': ['-prioridade', '-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['loja_config', 'sku'], name='estoque_pro_loja_co_0bd7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['shopify_product_id'], name='estoque_pro_shopify_91fb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['shopify_variant_id'], name='estoque_pro_shopify_33c044_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['estoque_atual'], name='estoque_pro_estoque_aba408_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['ativo'], name='estoque_pro_ativo_3ecea4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoestoque',
            unique_together={('loja_config', 'sku')},
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', 'data_movimentacao'], name='estoque_mov_produto_583b10_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo_movimento'], name='estoque_mov_tipo_mo_6231ac_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['pedido_shopify_id'], name='estoque_mov_pedido__4af4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['data_movimentacao'], name='estoque_mov_data_mo_0017da_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['produto', 'status'], name='estoque_ale_produto_be5652_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['tipo_alerta', 'status'], name='estoque_ale_tipo_al_cdcd85_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['prioridade', 'data_criacao'], name='estoque_ale_priorid_4ef3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaestoque',
            index=models.Index(fields=['status'], name='estoque_ale_status_e14d26_idx'),
        ),
    ]
