# Generated by Django 5.2 on 2025-08-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoestoque',
            name='fornecedor',
            field=models.CharField(choices=[('Dropi', 'Dropi'), ('PrimeCod', 'PrimeCod'), ('Ecomhub', 'Ecomhub'), ('N1', 'N1')], default='N1', max_length=20, verbose_name='Fornecedor'),
        ),
    ]
