# Generated by Django 5.2 on 2025-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produtoestoque_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoestoque',
            name='fornecedor',
            field=models.CharField(choices=[('Dropi', 'Dropi'), ('PrimeCod', 'PrimeCod'), ('Ecomhub', 'Ecomhub'), ('N1', 'N1'), ('N1 Itália', 'N1 Itália'), ('N1 Romênia', 'N1 Romênia'), ('N1 Polônia', 'N1 Polônia')], default='N1', max_length=50, verbose_name='Fornecedor'),
        ),
    ]
