# Generated by Django 5.2 on 2025-09-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produtoestoque_fornecedor'),
        ('processamento', '0009_shopifyconfig_webhook_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('fornecedor', models.CharField(choices=[('Dropi', 'Dropi'), ('PrimeCod', 'PrimeCod'), ('Ecomhub', 'Ecomhub'), ('N1', 'N1'), ('N1 Itália', 'N1 Itália'), ('N1 Romênia', 'N1 Romênia'), ('N1 Polônia', 'N1 Polônia')], default='N1', max_length=50, verbose_name='Fornecedor')),
                ('estoque_compartilhado', models.IntegerField(default=0, verbose_name='Estoque compartilhado')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque mínimo')),
                ('estoque_maximo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Estoque máximo')),
                ('alerta_estoque_baixo', models.BooleanField(default=True, verbose_name='Alertar estoque baixo')),
                ('alerta_estoque_zero', models.BooleanField(default=True, verbose_name='Alertar estoque zerado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto ativo')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo unitário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(blank=True, help_text='ID do produto no Shopify', null=True)),
                ('shopify_variant_id', models.BigIntegerField(blank=True, help_text='ID da variação no Shopify', null=True)),
                ('sync_shopify_enabled', models.BooleanField(default=True, verbose_name='Sincronizar com Shopify')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('erro_sincronizacao', models.TextField(blank=True, verbose_name='Erro na sincronização')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de venda')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo nesta loja')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.shopifyconfig')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Produto por Loja',
                'verbose_name_plural': 'Produtos por Loja',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='lojas',
            field=models.ManyToManyField(related_name='produtos', through='estoque.ProdutoLoja', to='processamento.shopifyconfig'),
        ),
        migrations.CreateModel(
            name='ProdutoSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU único', max_length=100, unique=True)),
                ('descricao_variacao', models.CharField(blank=True, max_length=255, verbose_name='Descrição da variação')),
                ('ativo', models.BooleanField(default=True, verbose_name='SKU ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'SKU do Produto',
                'verbose_name_plural': 'SKUs dos Produtos',
                'ordering': ['produto', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoqueCompartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('perda', 'Perda'), ('transferencia', 'Transferência'), ('sync_shopify', 'Sincronização Shopify')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('estoque_anterior', models.IntegerField(verbose_name='Estoque anterior')),
                ('estoque_posterior', models.IntegerField(verbose_name='Estoque posterior')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido_shopify_id', models.BigIntegerField(blank=True, help_text='ID do pedido no Shopify', null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total')),
                ('origem_sync', models.CharField(blank=True, help_text='Origem da sincronização (shopify, manual, api)', max_length=50)),
                ('dados_sync', models.JSONField(default=dict, help_text='Dados adicionais da sincronização')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP de origem da operação', null=True)),
                ('loja_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processamento.shopifyconfig', verbose_name='Loja de origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque Compartilhado',
                'verbose_name_plural': 'Movimentações de Estoque Compartilhado',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['produto', 'data_movimentacao'], name='estoque_mov_produto_b76a6f_idx'), models.Index(fields=['tipo_movimento'], name='estoque_mov_tipo_mo_52daeb_idx'), models.Index(fields=['loja_origem'], name='estoque_mov_loja_or_d7499b_idx'), models.Index(fields=['pedido_shopify_id'], name='estoque_mov_pedido__1eb3b2_idx'), models.Index(fields=['data_movimentacao'], name='estoque_mov_data_mo_96eb32_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoqueCompartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('estoque_zero', 'Estoque Zerado'), ('estoque_negativo', 'Estoque Negativo'), ('erro_sync', 'Erro de Sincronização'), ('produto_inativo', 'Produto Inativo'), ('limite_maximo', 'Limite Máximo Atingido'), ('movimentacao_suspeita', 'Movimentação Suspeita')], max_length=25, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('lido', 'Lido'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_contexto', models.JSONField(default=dict, help_text='Dados contextuais do alerta')),
                ('valor_atual', models.IntegerField(help_text='Valor atual que gerou o alerta')),
                ('valor_limite', models.IntegerField(blank=True, help_text='Valor limite configurado', null=True)),
                ('acao_sugerida', models.TextField(blank=True, verbose_name='Ação sugerida')),
                ('pode_resolver_automaticamente', models.BooleanField(default=False, verbose_name='Resolução automática')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('primeira_ocorrencia', models.DateTimeField(auto_now_add=True)),
                ('ultima_ocorrencia', models.DateTimeField(auto_now=True)),
                ('contador_ocorrencias', models.IntegerField(default=1, verbose_name='Número de ocorrências')),
                ('usuario_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_compartilhados_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque Compartilhado',
                'verbose_name_plural': 'Alertas de Estoque Compartilhado',
                'ordering': ['-prioridade', '-data_criacao'],
                'indexes': [models.Index(fields=['produto', 'status'], name='estoque_ale_produto_4606b6_idx'), models.Index(fields=['tipo_alerta', 'status'], name='estoque_ale_tipo_al_01672c_idx'), models.Index(fields=['prioridade', 'data_criacao'], name='estoque_ale_priorid_2206fb_idx'), models.Index(fields=['status'], name='estoque_ale_status_5a1e43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produtoloja',
            index=models.Index(fields=['produto', 'loja'], name='estoque_pro_produto_8435de_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoloja',
            index=models.Index(fields=['shopify_product_id'], name='estoque_pro_shopify_c6ea4b_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoloja',
            index=models.Index(fields=['shopify_variant_id'], name='estoque_pro_shopify_a3a946_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoloja',
            index=models.Index(fields=['ativo'], name='estoque_pro_ativo_ba8f75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoloja',
            unique_together={('produto', 'loja')},
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['user', 'ativo'], name='estoque_pro_user_id_37a02e_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['estoque_compartilhado'], name='estoque_pro_estoque_bf697d_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['fornecedor'], name='estoque_pro_fornece_e19553_idx'),
        ),
        migrations.AddIndex(
            model_name='produtosku',
            index=models.Index(fields=['sku'], name='estoque_pro_sku_54be37_idx'),
        ),
        migrations.AddIndex(
            model_name='produtosku',
            index=models.Index(fields=['produto', 'ativo'], name='estoque_pro_produto_f79d41_idx'),
        ),
    ]
