# Generated by Django 5.2 on 2025-09-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_add_produto_compartilhado_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosku',
            name='sku',
            field=models.CharField(help_text='SKU único por produto', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='produtosku',
            unique_together={('produto', 'sku')},
        ),
    ]
