# Generated by Django 5.2 on 2025-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_fix_sku_unique_constraint'),
    ]

    operations = [
        # Deletar tabelas de alertas (Django remove índices e constraints automaticamente)
        migrations.DeleteModel(
            name='AlertaEstoque',
        ),
        migrations.DeleteModel(
            name='AlertaEstoqueCompartilhado',
        ),
    ]
