# Generated by Django 5.2 on 2025-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_alertas_sistema'),
    ]

    operations = [
        # Alterar campo SKU para documentar que é único globalmente
        migrations.AlterField(
            model_name='produtosku',
            name='sku',
            field=models.CharField(help_text='SKU único em todo o sistema', max_length=100),
        ),

        # Adicionar constraint de SKU único global
        # Nota: Se já existir, PostgreSQL vai ignorar (idempotente)
        migrations.AddConstraint(
            model_name='produtosku',
            constraint=models.UniqueConstraint(
                fields=('sku',),
                name='unique_sku_global',
                violation_error_message='Este SKU já existe em outro produto. SKUs devem ser únicos em todo o sistema.'
            ),
        ),
    ]
