# Generated by Django 5.2 on 2025-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_cleanup_duplicate_skus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produtosku',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='produtosku',
            name='sku',
            field=models.CharField(help_text='SKU único em todo o sistema', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='produtosku',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_sku_global', violation_error_message='Este SKU já existe em outro produto. SKUs devem ser únicos em todo o sistema.'),
        ),
    ]
