# Generated by Django 5.2 on 2025-11-12 18:43

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove unique_together antigo do ProdutoSKU.
    Usa SeparateDatabaseAndState para evitar erros se a constraint não existir.
    A constraint correta (unique_sku_global) já foi adicionada na migration 0008.
    """

    dependencies = [
        ('estoque', '0008_add_unique_sku_constraint'),
    ]

    operations = [
        # Separar estado do Django vs operações de banco
        # Isso atualiza o estado do migrations sem falhar se a constraint não existir
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Atualizar estado do Django migrations
                migrations.AlterUniqueTogether(
                    name='produtosku',
                    unique_together=set(),
                ),
            ],
            database_operations=[
                # Não fazer nada no banco (constraint pode não existir)
                # A constraint correta já está em 0008
            ]
        ),
    ]
