FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn==21.2.0
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["python", "manage.py", "start_worker"]