[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --timeout 120 --preload'"
healthcheckPath = "/api/debug/cors/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10