[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate && mkdir -p staticfiles/media && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level info --timeout 1800 --keep-alive 300 --max-requests 0'"
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3