# Generated by Django 5.2 on 2025-07-01 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do projeto', max_length=200, verbose_name='Nome do Projeto')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now, help_text='Data de início do projeto', verbose_name='Data de Criação')),
                ('descricao', models.TextField(help_text='Descrição completa do que o projeto faz', verbose_name='Descrição Detalhada')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('arquivado', 'Arquivado'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status do Projeto')),
                ('link_projeto', models.URLField(blank=True, help_text='URL de acesso ao projeto', null=True, verbose_name='Link do Projeto')),
                ('ferramentas_tecnologias', models.JSONField(default=list, help_text='Lista de ferramentas e tecnologias utilizadas', verbose_name='Ferramentas/Tecnologias')),
                ('versao_atual', models.CharField(default='1.0.0', help_text='Versão atual do projeto (ex: 1.2.0)', max_length=20, verbose_name='Versão Atual')),
                ('tipo_projeto', models.CharField(choices=[('automacao', 'Automação'), ('chatbot', 'Chatbot'), ('analise_preditiva', 'Análise Preditiva'), ('visao_computacional', 'Visão Computacional'), ('processamento_nlp', 'Processamento de Linguagem Natural'), ('integracao_api', 'Integração de APIs'), ('dashboard_bi', 'Dashboard BI'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Projeto')),
                ('departamento_atendido', models.CharField(choices=[('ti', 'TI'), ('marketing', 'Marketing'), ('vendas', 'Vendas'), ('operacional', 'Operacional'), ('financeiro', 'Financeiro'), ('rh', 'Recursos Humanos'), ('atendimento', 'Atendimento ao Cliente'), ('diretoria', 'Diretoria')], max_length=20, verbose_name='Departamento Atendido')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade')),
                ('complexidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Complexidade')),
                ('usuarios_impactados', models.PositiveIntegerField(default=0, help_text='Quantidade estimada de usuários que usam o projeto', verbose_name='Usuários Impactados')),
                ('frequencia_uso', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('eventual', 'Eventual')], default='diario', max_length=15, verbose_name='Frequência de Uso')),
                ('horas_totais', models.DecimalField(decimal_places=2, help_text='Total de horas investidas no desenvolvimento', max_digits=8, verbose_name='Horas Totais de Desenvolvimento')),
                ('horas_desenvolvimento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Horas de Desenvolvimento')),
                ('horas_testes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Horas de Testes')),
                ('horas_documentacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Horas de Documentação')),
                ('horas_deploy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Horas de Deploy/Configuração')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=150.0, help_text='Valor cobrado por hora de desenvolvimento', max_digits=8, verbose_name='Valor por Hora (R$)')),
                ('custo_ferramentas_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Custo mensal com ferramentas e licenças', max_digits=10, verbose_name='Custos de Ferramentas/Licenças (Mensal)')),
                ('custo_apis_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Custo mensal com APIs e serviços externos', max_digits=10, verbose_name='Custos de APIs (Mensal)')),
                ('custo_infraestrutura_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Custo mensal com servidores, cloud, hosting', max_digits=10, verbose_name='Custos de Infraestrutura (Mensal)')),
                ('custo_manutencao_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Custo mensal com manutenção e suporte', max_digits=10, verbose_name='Custos de Manutenção (Mensal)')),
                ('custo_treinamentos', models.DecimalField(decimal_places=2, default=0, help_text='Custo único com treinamentos', max_digits=10, verbose_name='Custos de Treinamentos')),
                ('custo_consultoria', models.DecimalField(decimal_places=2, default=0, help_text='Custo único com consultoria externa', max_digits=10, verbose_name='Custos de Consultoria Externa')),
                ('custo_setup_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Custo único com configuração inicial', max_digits=10, verbose_name='Custos de Setup Inicial')),
                ('economia_horas_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de horas economizadas mensalmente', max_digits=10, verbose_name='Horas Economizadas por Mês')),
                ('valor_hora_economizada', models.DecimalField(decimal_places=2, default=50.0, help_text='Valor estimado da hora economizada', max_digits=8, verbose_name='Valor da Hora Economizada (R$)')),
                ('reducao_erros_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Valor mensal economizado com redução de erros', max_digits=10, verbose_name='Economia com Redução de Erros (Mensal)')),
                ('economia_outros_mensais', models.DecimalField(decimal_places=2, default=0, help_text='Outras economias mensais (produtividade, etc.)', max_digits=10, verbose_name='Outras Economias (Mensal)')),
                ('documentacao_tecnica', models.URLField(blank=True, null=True, verbose_name='Link da Documentação Técnica')),
                ('licoes_aprendidas', models.TextField(blank=True, help_text='O que funcionou bem e quais foram os desafios', verbose_name='Lições Aprendidas')),
                ('proximos_passos', models.TextField(blank=True, help_text='Melhorias e funcionalidades planejadas', verbose_name='Próximos Passos')),
                ('data_revisao', models.DateField(blank=True, help_text='Quando o projeto será reavaliado', null=True, verbose_name='Data de Próxima Revisão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Se o projeto está ativo no sistema', verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_ia_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criadores', models.ManyToManyField(help_text='Usuários responsáveis pelo projeto', related_name='projetos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criadores/Responsáveis')),
                ('dependencias', models.ManyToManyField(blank=True, help_text='Outros projetos dos quais este depende', related_name='projetos_dependentes', to='ia.projetoia', verbose_name='Dependências')),
            ],
            options={
                'verbose_name': 'Projeto de IA',
                'verbose_name_plural': 'Projetos de IA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VersaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(help_text='Número da versão (ex: 1.2.0)', max_length=20, verbose_name='Versão')),
                ('versao_anterior', models.CharField(blank=True, max_length=20, verbose_name='Versão Anterior')),
                ('motivo_mudanca', models.TextField(help_text='Descrição das alterações realizadas', verbose_name='Motivo da Mudança')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Lançamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='ia.projetoia', verbose_name='Projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Alteração')),
            ],
            options={
                'verbose_name': 'Versão do Projeto',
                'verbose_name_plural': 'Versões dos Projetos',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['status', 'ativo'], name='ia_projetoi_status_346549_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['tipo_projeto', 'departamento_atendido'], name='ia_projetoi_tipo_pr_6069e9_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['prioridade', 'complexidade'], name='ia_projetoi_priorid_704d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['criado_em'], name='ia_projetoi_criado__40f9ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='versaoprojeto',
            unique_together={('projeto', 'versao')},
        ),
    ]
