# Generated by Django 5.2 on 2025-07-03 16:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_adicionar_departamentos_multiplos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projetoia',
            name='ia_projetoi_tipo_pr_6069e9_idx',
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_apis_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custos de APIs (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_consultoria',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo único com consultoria externa', max_digits=10, verbose_name='Custos de Consultoria (R$)'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_ferramentas_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custos de Ferramentas/Licenças (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_infraestrutura_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custos de Infraestrutura (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_manutencao_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custos de Manutenção (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_setup_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo único com configuração inicial', max_digits=10, verbose_name='Custos de Setup Inicial (R$)'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='custo_treinamentos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo único com treinamentos', max_digits=10, verbose_name='Custos de Treinamentos (R$)'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today, help_text='Data de início do projeto', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='economia_horas_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas Economizadas por Mês [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='economia_outros_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outras Economias (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='reducao_erros_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Economia com Redução de Erros (Mensal) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Campo legado - usar custo_hora_empresa', max_digits=8, verbose_name='Valor por Hora (R$) [LEGADO]'),
        ),
        migrations.AlterField(
            model_name='projetoia',
            name='valor_hora_economizada',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Valor da Hora Economizada (R$) [LEGADO]'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['tipo_projeto', 'departamentos_atendidos'], name='ia_projetoi_tipo_pr_b32291_idx'),
        ),
    ]
