# Generated by Django 5.2 on 2025-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_corrigir_dados_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoia',
            name='documentacao_apoio',
            field=models.URLField(blank=True, help_text='Link para documentação adicional que serve como apoio', null=True, verbose_name='Documentação de Apoio'),
        ),
    ]
