# Generated by Django 5.2 on 2025-08-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_projetoia_documentacao_apoio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetoia',
            name='horas_totais',
        ),
    ]
