# Generated by Django 5.2 on 2025-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_remove_horas_totais_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoia',
            name='tipo_projeto',
            field=models.CharField(choices=[('automacao', 'Automação'), ('chatbot', 'ChatBot'), ('agente', 'Agente'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Projeto'),
        ),
    ]
