# Generated by Django 5.2 on 2025-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0009_ajustar_tipos_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoia',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('em_construcao', 'Em Construção'), ('manutencao', 'Em Manutenção'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status do Projeto'),
        ),
    ]
