# Generated by Django 5.2 on 2025-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0010_adicionar_status_em_construcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoia',
            name='documentacao_apoio',
            field=models.TextField(blank=True, help_text='Links para documentação adicional que serve como apoio (separados por linha)', null=True, verbose_name='Documentação de Apoio'),
        ),
    ]
