# Generated by Django 5.2 on 2025-08-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0011_alterar_documentacao_apoio_para_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador da Business Manager', max_length=200, verbose_name='Nome da Business Manager')),
                ('business_manager_id', models.CharField(help_text='ID único da Business Manager no Facebook', max_length=50, unique=True, verbose_name='ID da Business Manager')),
                ('access_token_encrypted', models.TextField(help_text='Token de acesso criptografado para API do WhatsApp', verbose_name='Token de Acesso (Criptografado)')),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Token para verificação do webhook', max_length=200, verbose_name='Token de Verificação do Webhook')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta Business Manager está ativa para monitoramento', verbose_name='Ativo')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, help_text='Data/hora da última sincronização com a API', null=True, verbose_name='Última Sincronização')),
                ('erro_ultima_sincronizacao', models.TextField(blank=True, help_text='Detalhes do erro caso a última sincronização tenha falhado', verbose_name='Erro na Última Sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Business Manager',
                'verbose_name_plural': 'Business Managers',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('quality_degraded', 'Qualidade Degradada'), ('limit_reduced', 'Limite Reduzido'), ('status_changed', 'Status Alterado'), ('disconnected', 'Desconectado'), ('restricted', 'Restrito')], max_length=30, verbose_name='Tipo de Alerta')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Alerta')),
                ('descricao', models.TextField(help_text='Descrição detalhada do que aconteceu', verbose_name='Descrição')),
                ('valor_anterior', models.CharField(blank=True, max_length=50, verbose_name='Valor Anterior')),
                ('valor_atual', models.CharField(blank=True, max_length=50, verbose_name='Valor Atual')),
                ('visualizado', models.BooleanField(default=False, help_text='Se o alerta foi visualizado pelo usuário', verbose_name='Visualizado')),
                ('resolvido', models.BooleanField(default=False, help_text='Se o alerta foi marcado como resolvido', verbose_name='Resolvido')),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Visualização')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('comentario_resolucao', models.TextField(blank=True, help_text='Comentário sobre como o alerta foi resolvido', verbose_name='Comentário da Resolução')),
                ('notificacao_enviada', models.BooleanField(default=False, help_text='Se a notificação foi enviada via email/webhook', verbose_name='Notificação Enviada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Alerta de Qualidade',
                'verbose_name_plural': 'Alertas de Qualidade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='QualityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.CharField(choices=[('GREEN', 'Verde (Boa)'), ('YELLOW', 'Amarela (Atenção)'), ('RED', 'Vermelha (Baixa)'), ('NA', 'Não Disponível')], max_length=10, verbose_name='Classificação de Qualidade')),
                ('messaging_limit_tier', models.CharField(choices=[('TIER_50', '50 mensagens/dia'), ('TIER_250', '250 mensagens/dia'), ('TIER_1000', '1.000 mensagens/dia'), ('TIER_UNLIMITED', 'Ilimitado')], max_length=20, verbose_name='Limite de Mensagens')),
                ('status', models.CharField(choices=[('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('FLAGGED', 'Sinalizado'), ('RESTRICTED', 'Restrito')], max_length=15, verbose_name='Status')),
                ('quality_rating_anterior', models.CharField(blank=True, choices=[('GREEN', 'Verde (Boa)'), ('YELLOW', 'Amarela (Atenção)'), ('RED', 'Vermelha (Baixa)'), ('NA', 'Não Disponível')], max_length=10, null=True, verbose_name='Qualidade Anterior')),
                ('messaging_limit_tier_anterior', models.CharField(blank=True, choices=[('TIER_50', '50 mensagens/dia'), ('TIER_250', '250 mensagens/dia'), ('TIER_1000', '1.000 mensagens/dia'), ('TIER_UNLIMITED', 'Ilimitado')], max_length=20, null=True, verbose_name='Limite Anterior')),
                ('status_anterior', models.CharField(blank=True, choices=[('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('FLAGGED', 'Sinalizado'), ('RESTRICTED', 'Restrito')], max_length=15, null=True, verbose_name='Status Anterior')),
                ('houve_mudanca_qualidade', models.BooleanField(default=False, verbose_name='Mudança na Qualidade')),
                ('houve_mudanca_limite', models.BooleanField(default=False, verbose_name='Mudança no Limite')),
                ('houve_mudanca_status', models.BooleanField(default=False, verbose_name='Mudança no Status')),
                ('dados_api_completos', models.JSONField(default=dict, help_text='Resposta completa da API no momento da captura', verbose_name='Dados Completos da API')),
                ('capturado_em', models.DateTimeField(auto_now_add=True, verbose_name='Capturado em')),
            ],
            options={
                'verbose_name': 'Histórico de Qualidade',
                'verbose_name_plural': 'Histórico de Qualidade',
                'ordering': ['-capturado_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(help_text='ID único do número na API do WhatsApp', max_length=50, unique=True, verbose_name='ID do Número')),
                ('display_phone_number', models.CharField(help_text='Número formatado para exibição', max_length=20, verbose_name='Número de Telefone')),
                ('verified_name', models.CharField(blank=True, help_text='Nome verificado na conta WhatsApp Business', max_length=200, verbose_name='Nome Verificado')),
                ('quality_rating', models.CharField(choices=[('GREEN', 'Verde (Boa)'), ('YELLOW', 'Amarela (Atenção)'), ('RED', 'Vermelha (Baixa)'), ('NA', 'Não Disponível')], default='NA', max_length=10, verbose_name='Classificação de Qualidade')),
                ('messaging_limit_tier', models.CharField(choices=[('TIER_50', '50 mensagens/dia'), ('TIER_250', '250 mensagens/dia'), ('TIER_1000', '1.000 mensagens/dia'), ('TIER_UNLIMITED', 'Ilimitado')], default='TIER_50', max_length=20, verbose_name='Limite de Mensagens')),
                ('status', models.CharField(choices=[('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('FLAGGED', 'Sinalizado'), ('RESTRICTED', 'Restrito')], default='CONNECTED', max_length=15, verbose_name='Status')),
                ('monitoramento_ativo', models.BooleanField(default=True, help_text='Se este número deve ser monitorado automaticamente', verbose_name='Monitoramento Ativo')),
                ('frequencia_verificacao_minutos', models.PositiveIntegerField(default=60, help_text='Intervalo em minutos para verificar este número', verbose_name='Frequência de Verificação (minutos)')),
                ('detalhes_api', models.JSONField(default=dict, help_text='Dados completos retornados pela API do WhatsApp', verbose_name='Detalhes da API')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultima_verificacao', models.DateTimeField(blank=True, help_text='Data/hora da última verificação na API', null=True, verbose_name='Última Verificação')),
            ],
            options={
                'verbose_name': 'Número WhatsApp Business',
                'verbose_name_plural': 'Números WhatsApp Business',
                'ordering': ['display_phone_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='projetoia',
            name='ia_projetoi_tipo_pr_b32291_idx',
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp'], name='ia_logentry_timesta_cee95f_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['tipo_projeto'], name='ia_projetoi_tipo_pr_0871ba_idx'),
        ),
        migrations.AddIndex(
            model_name='projetoia',
            index=models.Index(fields=['departamento_atendido'], name='ia_projetoi_departa_2c2e7e_idx'),
        ),
        migrations.AddField(
            model_name='businessmanager',
            name='responsavel',
            field=models.ForeignKey(help_text='Usuário responsável por esta Business Manager', on_delete=django.db.models.deletion.PROTECT, related_name='business_managers', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='usuario_que_resolveu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='usuario_que_visualizou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_visualizados', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por'),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='quality_history',
            field=models.ForeignKey(blank=True, help_text='Registro do histórico que gerou este alerta', null=True, on_delete=django.db.models.deletion.CASCADE, to='ia.qualityhistory', verbose_name='Histórico Relacionado'),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='business_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='ia.businessmanager', verbose_name='Business Manager'),
        ),
        migrations.AddField(
            model_name='qualityhistory',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_history', to='ia.whatsappphonenumber', verbose_name='Número WhatsApp'),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ia.whatsappphonenumber', verbose_name='Número WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='businessmanager',
            index=models.Index(fields=['ativo', 'ultima_sincronizacao'], name='ia_business_ativo_05ad32_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmanager',
            index=models.Index(fields=['business_manager_id'], name='ia_business_busines_acd1da_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['quality_rating', 'monitoramento_ativo'], name='ia_whatsapp_quality_f2207b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['status', 'monitoramento_ativo'], name='ia_whatsapp_status_958021_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['ultima_verificacao'], name='ia_whatsapp_ultima__1834a2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['phone_number_id'], name='ia_whatsapp_phone_n_c2ed23_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityhistory',
            index=models.Index(fields=['phone_number', '-capturado_em'], name='ia_qualityh_phone_n_845afc_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityhistory',
            index=models.Index(fields=['quality_rating', '-capturado_em'], name='ia_qualityh_quality_e9c80b_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityhistory',
            index=models.Index(fields=['houve_mudanca_qualidade', '-capturado_em'], name='ia_qualityh_houve_m_511acb_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityhistory',
            index=models.Index(fields=['houve_mudanca_limite', '-capturado_em'], name='ia_qualityh_houve_m_c3d14a_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityhistory',
            index=models.Index(fields=['houve_mudanca_status', '-capturado_em'], name='ia_qualityh_houve_m_9ebaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['phone_number', '-criado_em'], name='ia_qualitya_phone_n_779e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['alert_type', 'priority', '-criado_em'], name='ia_qualitya_alert_t_be536e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['visualizado', 'resolvido', '-criado_em'], name='ia_qualitya_visuali_be152e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['priority', 'visualizado', '-criado_em'], name='ia_qualitya_priorit_e8575f_idx'),
        ),
    ]
