# Generated by Django 5.2 on 2024-XX-XX XX:XX

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0012_businessmanager_qualityalert_qualityhistory_and_more'),
    ]

    operations = [
        # Renomear o modelo BusinessManager para WhatsAppBusinessAccount
        migrations.RenameModel(
            old_name='BusinessManager',
            new_name='WhatsAppBusinessAccount',
        ),
        
        # Renomear o campo business_manager_id para whatsapp_business_account_id
        migrations.RenameField(
            model_name='whatsappbusinessaccount',
            old_name='business_manager_id',
            new_name='whatsapp_business_account_id',
        ),
        
        # Atualizar campos de relacionamento em outros modelos
        migrations.RenameField(
            model_name='whatsappphonenumber',
            old_name='business_manager',
            new_name='whatsapp_business_account',
        ),
        
        # Atualizar verbose_name e help_text
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='nome',
            field=models.CharField(
                help_text='Nome identificador da WhatsApp Business Account',
                max_length=200,
                verbose_name='Nome da WhatsApp Business Account'
            ),
        ),
        
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='whatsapp_business_account_id',
            field=models.CharField(
                help_text='ID único da WhatsApp Business Account (WABA ID)',
                max_length=50,
                unique=True,
                verbose_name='WhatsApp Business Account ID (WABA ID)'
            ),
        ),
        
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='responsavel',
            field=models.ForeignKey(
                help_text='Usuário responsável por esta WhatsApp Business Account',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='whatsapp_business_accounts',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Responsável'
            ),
        ),
        
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='whatsapp_business_account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='phone_numbers',
                to='ia.whatsappbusinessaccount',
                verbose_name='WhatsApp Business Account'
            ),
        ),
        
        # Atualizar Meta class
        migrations.AlterModelOptions(
            name='whatsappbusinessaccount',
            options={
                'ordering': ['nome'],
                'verbose_name': 'WhatsApp Business Account',
                'verbose_name_plural': 'WhatsApp Business Accounts'
            },
        ),
    ]