# Generated by Django 5.2 on 2025-09-12 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0013_rename_business_manager_to_waba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappbusinessaccount',
            name='ia_business_busines_acd1da_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappbusinessaccount',
            new_name='ia_whatsapp_ativo_923c11_idx',
            old_name='ia_business_ativo_05ad32_idx',
        ),
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se esta WhatsApp Business Account está ativa para monitoramento', verbose_name='Ativo'),
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['whatsapp_business_account_id'], name='ia_whatsapp_whatsap_5eaa87_idx'),
        ),
    ]
