# Generated by Django 5.2 on 2025-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0014_remove_whatsappbusinessaccount_ia_business_busines_acd1da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='bm_nome_customizado',
            field=models.CharField(blank=True, help_text='Nome personalizado para identificar a Business Manager', max_length=200, null=True, verbose_name='Nome Customizado da Business Manager'),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='pais_nome_customizado',
            field=models.CharField(blank=True, help_text='Nome personalizado para identificar o país', max_length=100, null=True, verbose_name='Nome Customizado do País'),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='perfil',
            field=models.TextField(blank=True, help_text='Descrição livre do perfil do número WhatsApp', null=True, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='token_expira_em',
            field=models.DateField(blank=True, help_text='Data em que o token de acesso expira', null=True, verbose_name='Data de Expiração do Token'),
        ),
    ]
