# Generated by Django 5.2 on 2025-10-16 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0015_adicionar_campos_customizados_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NicochatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador desta configuração NicoChat', max_length=200, verbose_name='Nome da Configuração')),
                ('api_key_encrypted', models.TextField(help_text='API Key do NicoChat armazenada de forma segura', verbose_name='API Key Criptografada')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(help_text='Usuário responsável por esta configuração', on_delete=django.db.models.deletion.CASCADE, related_name='nicochat_configs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração NicoChat',
                'verbose_name_plural': 'Configurações NicoChat',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='ia_nicochat_usuario_f909cb_idx'), models.Index(fields=['criado_em'], name='ia_nicochat_criado__9f6a44_idx')],
            },
        ),
    ]
