# Generated by Django 5.2 on 2025-10-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0016_nicochatconfig'),
    ]

    operations = [
        # 1. Renomear a tabela no banco de dados
        migrations.RenameModel(
            old_name='NicochatConfig',
            new_name='NicochatWorkspace',
        ),

        # 2. Adicionar novo campo limite_contatos
        migrations.AddField(
            model_name='nicochatworkspace',
            name='limite_contatos',
            field=models.PositiveIntegerField(
                default=1000,
                verbose_name='Limite de Contatos',
                help_text='Número máximo de contatos permitidos neste workspace'
            ),
        ),

        # 3. Atualizar Meta do model
        migrations.AlterModelOptions(
            name='nicochatworkspace',
            options={
                'verbose_name': 'Workspace NicoChat',
                'verbose_name_plural': 'Workspaces NicoChat',
                'ordering': ['-criado_em'],
            },
        ),
    ]
