# Generated by Django 5.2 on 2025-10-21 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0017_rename_nicochatconfig_to_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nicochatworkspace',
            new_name='ia_nicochat_usuario_73da28_idx',
            old_name='ia_nicochat_usuario_f909cb_idx',
        ),
        migrations.RenameIndex(
            model_name='nicochatworkspace',
            new_name='ia_nicochat_criado__f7429c_idx',
            old_name='ia_nicochat_criado__9f6a44_idx',
        ),
        migrations.AddField(
            model_name='nicochatworkspace',
            name='tipo_whatsapp',
            field=models.CharField(blank=True, choices=[('cloud', 'WhatsApp Cloud API'), ('qr_code', 'WhatsApp QR Code')], help_text='Tipo de conexão WhatsApp (Cloud API ou QR Code)', max_length=10, null=True, verbose_name='Tipo de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='nicochatworkspace',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se este workspace está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='nicochatworkspace',
            name='nome',
            field=models.CharField(help_text='Nome identificador deste workspace NicoChat', max_length=200, verbose_name='Nome do Workspace'),
        ),
        migrations.AlterField(
            model_name='nicochatworkspace',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário responsável por este workspace', on_delete=django.db.models.deletion.CASCADE, related_name='nicochat_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
