# Generated by Django 5.2 on 2025-08-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
