# Generated by Django 5.2 on 2025-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='categoria',
            field=models.CharField(choices=[('bug', 'Bug/Erro'), ('melhoria', 'Sugestão de melhoria'), ('outro', 'Outro')], max_length=20),
        ),
    ]
