# Generated by Django 5.2 on 2025-08-08 15:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
