# Generated by Django 5.2 on 2025-09-01 23:24

import features.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=features.feedback.models.feedback_image_upload_path),
        ),
    ]
