# Generated by Django 5.2 on 2025-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_primecod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseprimecod',
            name='dados_processados',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Processados (Frontend)'),
        ),
        migrations.AddField(
            model_name='analiseprimecod',
            name='tipo',
            field=models.CharField(default='PRIMECOD', max_length=20, verbose_name='Tipo de Análise'),
        ),
    ]
