# Generated by Django 5.2 on 2025-11-25 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_primecod', '0002_analiseprimecod_dados_processados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeCODCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primecod_id', models.IntegerField(unique=True, verbose_name='ID PrimeCOD')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('stock_label', models.CharField(blank=True, help_text='High/Medium/Low', max_length=20, verbose_name='Nível de Estoque')),
                ('total_units_sold', models.IntegerField(default=0, verbose_name='Total de Unidades Vendidas')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total de Pedidos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('countries', models.JSONField(default=list, help_text='Lista de países onde o produto está disponível', verbose_name='Países Disponíveis')),
                ('images', models.JSONField(default=list, help_text='URLs das imagens do produto', verbose_name='Imagens')),
                ('is_new', models.BooleanField(default=True, help_text='Produto visto pela primeira vez nas últimas 24h', verbose_name='Produto Novo')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Primeira Vez Visto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto Catálogo PrimeCOD',
                'verbose_name_plural': 'Produtos Catálogo PrimeCOD',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['primecod_id'], name='metricas_pr_primeco_5a4251_idx'), models.Index(fields=['sku'], name='metricas_pr_sku_f037de_idx'), models.Index(fields=['is_new', '-first_seen_at'], name='metricas_pr_is_new_aaa46a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrimeCODCatalogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('total_units_sold', models.IntegerField(verbose_name='Total de Unidades Vendidas')),
                ('snapshot_date', models.DateField(verbose_name='Data do Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='metricas_primecod.primecodcatalogproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Snapshot Catálogo PrimeCOD',
                'verbose_name_plural': 'Snapshots Catálogo PrimeCOD',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date'], name='metricas_pr_snapsho_17a5e0_idx'), models.Index(fields=['product', '-snapshot_date'], name='metricas_pr_product_7c3d9f_idx')],
                'unique_together': {('product', 'snapshot_date')},
            },
        ),
    ]
