# Generated by Django 5.2 on 2025-11-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_primecod', '0004_add_primecod_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro')], default='running', max_length=20, verbose_name='Status')),
                ('total_products_api', models.IntegerField(default=0, verbose_name='Total produtos API')),
                ('products_created', models.IntegerField(default=0, verbose_name='Produtos criados')),
                ('products_updated', models.IntegerField(default=0, verbose_name='Produtos atualizados')),
                ('products_error', models.IntegerField(default=0, verbose_name='Produtos com erro')),
                ('snapshots_created', models.IntegerField(default=0, verbose_name='Snapshots criados')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de erro')),
                ('error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de erro')),
            ],
            options={
                'verbose_name': 'Log de Sincronização do Catálogo',
                'verbose_name_plural': 'Logs de Sincronização do Catálogo',
                'db_table': 'metricas_primecod_catalogsynclog',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='idx_catalog_sync_started'), models.Index(fields=['status'], name='idx_catalog_sync_status')],
            },
        ),
    ]
