# Generated by Django 5.2 on 2025-11-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_primecod', '0005_catalogsynclog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='primecodcatalogsnapshot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='primecodcatalogsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(verbose_name='Data e Hora do Snapshot'),
        ),
    ]
