# Generated by Django 5.2 on 2025-07-04 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('LEADS', 'Status de Leads'), ('ORDERS', 'Status de Orders')], max_length=10)),
                ('status_original', models.CharField(max_length=100, verbose_name='Status Original')),
                ('status_mapeado', models.CharField(max_length=50, verbose_name='Status Mapeado')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mapeamento de Status',
                'verbose_name_plural': 'Mapeamentos de Status',
                'unique_together': {('categoria', 'status_original')},
            },
        ),
        migrations.CreateModel(
            name='AnaliseEfetividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Análise')),
                ('tipo', models.CharField(choices=[('PRIMECOD', 'Prime COD'), ('ECOMHUB', 'ECOMHUB')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dados_leads', models.JSONField(blank=True, null=True, verbose_name='Dados de Leads')),
                ('dados_efetividade', models.JSONField(blank=True, null=True, verbose_name='Dados de Efetividade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Análise de Efetividade',
                'verbose_name_plural': 'Análises de Efetividade',
                'ordering': ['-atualizado_em'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
    ]
