# Generated by Django 5.2 on 2025-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0002_shopifyconfig_nome_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentolog',
            name='tipo',
            field=models.CharField(choices=[('busca', 'Busca de Duplicatas'), ('busca_ip', 'Busca por IP'), ('cancelamento', 'Cancelamento Individual'), ('cancelamento_lote', 'Cancelamento em Lote'), ('erro', 'Erro')], max_length=20),
        ),
    ]
