# Generated by Django 5.2 on 2025-08-13 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0003_alter_processamentolog_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentolog',
            name='tipo',
            field=models.CharField(choices=[('busca', 'Busca de Duplicatas'), ('busca_ip', 'Busca por IP'), ('cancelamento', 'Cancelamento Individual'), ('cancelamento_lote', 'Cancelamento em Lote'), ('debug', 'Debug de Dados'), ('erro', 'Erro')], max_length=20),
        ),
        migrations.CreateModel(
            name='IPSecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ip_search', 'Busca por IP'), ('ip_detail_access', 'Acesso a Detalhes de IP'), ('massive_ip_search', 'Busca Massiva de IPs'), ('suspicious_activity', 'Atividade Suspeita'), ('rate_limit_exceeded', 'Rate Limit Excedido'), ('ip_not_found', 'IP Não Encontrado'), ('ip_search_error', 'Erro na Busca IP'), ('ip_detail_error', 'Erro no Detalhamento IP'), ('debug_shopify_raw_data', 'Debug de Dados RAW Shopify'), ('debug_shopify_error', 'Erro no Debug Shopify')], max_length=30)),
                ('user_ip', models.GenericIPAddressField(help_text='IP do usuário que fez a requisição')),
                ('user_agent', models.TextField(blank=True)),
                ('target_ip_hash', models.CharField(blank=True, help_text='Hash SHA256 do IP consultado', max_length=64)),
                ('target_ip_masked', models.CharField(blank=True, help_text='IP consultado completo', max_length=45)),
                ('details', models.JSONField(default=dict, help_text='Detalhes da operação')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], default='low', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria de Segurança IP',
                'verbose_name_plural': 'Logs de Auditoria de Segurança IP',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='processamen_user_id_cebe96_idx'), models.Index(fields=['timestamp'], name='processamen_timesta_0d9590_idx'), models.Index(fields=['risk_level'], name='processamen_risk_le_160c0f_idx'), models.Index(fields=['target_ip_hash'], name='processamen_target__8eac0d_idx')],
            },
        ),
    ]
