# Generated by Django 5.2 on 2025-08-13 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0004_alter_processamentolog_tipo_ipsecurityauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDetectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('taxa_baixa', 'Taxa de Detecção Baixa'), ('performance_degradada', 'Performance Degradada'), ('muitos_ips_suspeitos', 'Muitos IPs Suspeitos'), ('metodo_falhando', 'Método de Detecção Falhando'), ('api_externa_indisponivel', 'API Externa Indisponível'), ('dados_malformados', 'Dados Malformados Frequentes'), ('volume_anormal', 'Volume Anormal de Requisições'), ('threshold_configuravel', 'Threshold Configurável Atingido')], max_length=30)),
                ('severidade', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido'), ('false_positive', 'Falso Positivo')], default='active', max_length=15)),
                ('titulo', models.CharField(help_text='Título do alerta', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do problema')),
                ('dados_contexto', models.JSONField(default=dict, help_text='Dados que geraram o alerta')),
                ('valor_detectado', models.FloatField(help_text='Valor que disparou o alerta')),
                ('threshold_configurado', models.FloatField(help_text='Threshold que foi ultrapassado')),
                ('periodo_referencia', models.CharField(help_text="Período analisado (ex: '24h', '7d')", max_length=50)),
                ('sugestao_acao', models.TextField(blank=True, help_text='Sugestão automática de ação')),
                ('pode_resolver_automaticamente', models.BooleanField(default=False, help_text='Sistema pode resolver automaticamente')),
                ('primeira_ocorrencia', models.DateTimeField(help_text='Primeira vez que este problema foi detectado')),
                ('ultima_ocorrencia', models.DateTimeField(help_text='Última ocorrência do problema')),
                ('contagem_ocorrencias', models.IntegerField(default=1, help_text='Quantas vezes este problema ocorreu')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('reconhecido_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_alerts', to='processamento.shopifyconfig')),
                ('reconhecido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconhecidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Detecção IP',
                'verbose_name_plural': 'Alertas de Detecção IP',
                'ordering': ['-severidade', '-primeira_ocorrencia'],
                'indexes': [models.Index(fields=['config', 'status'], name='processamen_config__9e0081_idx'), models.Index(fields=['tipo_alerta', 'severidade'], name='processamen_tipo_al_bc2aaf_idx'), models.Index(fields=['status', 'primeira_ocorrencia'], name='processamen_status_81e572_idx'), models.Index(fields=['criado_em'], name='processamen_criado__3cac4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPDetectionDebugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único da sessão de análise', max_length=64)),
                ('order_id', models.CharField(help_text='ID do pedido analisado', max_length=50)),
                ('nivel', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('categoria', models.CharField(choices=[('ip_detection', 'Detecção de IP'), ('hierarchy_analysis', 'Análise de Hierarquia'), ('alternative_methods', 'Métodos Alternativos'), ('validation', 'Validação de IP'), ('geolocation', 'Geolocalização'), ('performance', 'Performance'), ('security', 'Segurança'), ('data_quality', 'Qualidade de Dados')], max_length=30)),
                ('subcategoria', models.CharField(blank=True, help_text='Subcategoria específica', max_length=50)),
                ('titulo', models.CharField(help_text='Título descritivo do log', max_length=200)),
                ('detalhes_json', models.JSONField(help_text='Dados estruturados em JSON')),
                ('ip_detectado', models.GenericIPAddressField(blank=True, help_text='IP que foi detectado (se houver)', null=True)),
                ('metodo_deteccao', models.CharField(blank=True, help_text='Método que detectou o IP', max_length=50)),
                ('score_confianca', models.FloatField(blank=True, help_text='Score de confiança (0.0-1.0)', null=True)),
                ('tempo_processamento_ms', models.FloatField(blank=True, help_text='Tempo de processamento em ms', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent do browser')),
                ('ip_requisicao', models.GenericIPAddressField(help_text='IP de quem fez a requisição')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('versao_sistema', models.CharField(default='2.0', help_text='Versão do sistema', max_length=20)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_logs', to='processamento.shopifyconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Debug de Detecção IP',
                'verbose_name_plural': 'Logs de Debug de Detecção IP',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['config', 'timestamp'], name='processamen_config__56213c_idx'), models.Index(fields=['session_id'], name='processamen_session_27be5d_idx'), models.Index(fields=['nivel', 'categoria'], name='processamen_nivel_903567_idx'), models.Index(fields=['order_id'], name='processamen_order_i_d8c4f5_idx'), models.Index(fields=['timestamp'], name='processamen_timesta_a0594f_idx'), models.Index(fields=['metodo_deteccao'], name='processamen_metodo__457301_idx'), models.Index(fields=['score_confianca'], name='processamen_score_c_284428_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPDetectionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência para estas estatísticas')),
                ('total_pedidos_processados', models.IntegerField(default=0, help_text='Total de pedidos analisados')),
                ('pedidos_com_ip_detectado', models.IntegerField(default=0, help_text='Pedidos onde foi possível detectar IP')),
                ('pedidos_sem_ip', models.IntegerField(default=0, help_text='Pedidos onde nenhum IP foi encontrado')),
                ('pedidos_ip_rejeitado', models.IntegerField(default=0, help_text='Pedidos onde IP foi rejeitado por filtros de segurança')),
                ('ips_via_client_details', models.IntegerField(default=0, help_text='IPs encontrados via client_details.browser_ip')),
                ('ips_via_customer_address', models.IntegerField(default=0, help_text='IPs encontrados via customer.default_address')),
                ('ips_via_shipping_address', models.IntegerField(default=0, help_text='IPs encontrados via shipping_address')),
                ('ips_via_billing_address', models.IntegerField(default=0, help_text='IPs encontrados via billing_address')),
                ('ips_via_metodos_alternativos', models.IntegerField(default=0, help_text='IPs encontrados via métodos alternativos')),
                ('ips_alta_confianca', models.IntegerField(default=0, help_text='IPs com confidence >= 0.8')),
                ('ips_media_confianca', models.IntegerField(default=0, help_text='IPs com 0.6 <= confidence < 0.8')),
                ('ips_baixa_confianca', models.IntegerField(default=0, help_text='IPs com confidence < 0.6')),
                ('ips_suspeitos_detectados', models.IntegerField(default=0, help_text='IPs identificados como suspeitos')),
                ('tempo_medio_deteccao_ms', models.FloatField(default=0, help_text='Tempo médio de detecção em milissegundos')),
                ('tempo_max_deteccao_ms', models.FloatField(default=0, help_text='Maior tempo de detecção registrado')),
                ('api_calls_externas', models.IntegerField(default=0, help_text='Chamadas para APIs externas de geolocalização')),
                ('taxa_sucesso_hierarquia', models.FloatField(default=0, help_text='% de sucesso do método hierárquico padrão')),
                ('taxa_sucesso_alternativo', models.FloatField(default=0, help_text='% de sucesso dos métodos alternativos')),
                ('taxa_sucesso_geral', models.FloatField(default=0, help_text='% de sucesso geral de detecção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('versao_detector', models.CharField(default='v2.0', help_text='Versão do detector usado', max_length=20)),
                ('dados_extras', models.JSONField(default=dict, help_text='Dados adicionais específicos')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_statistics', to='processamento.shopifyconfig')),
            ],
            options={
                'verbose_name': 'Estatística de Detecção de IP',
                'verbose_name_plural': 'Estatísticas de Detecção de IP',
                'ordering': ['-data_referencia', '-criado_em'],
                'indexes': [models.Index(fields=['config', 'data_referencia'], name='processamen_config__ad72ec_idx'), models.Index(fields=['data_referencia'], name='processamen_data_re_895fdb_idx'), models.Index(fields=['taxa_sucesso_geral'], name='processamen_taxa_su_41bca2_idx'), models.Index(fields=['criado_em'], name='processamen_criado__4be91c_idx')],
                'unique_together': {('config', 'data_referencia')},
            },
        ),
    ]
