# Generated by Django 5.2 on 2025-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0005_ipdetectionalert_ipdetectiondebuglog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentolog',
            name='tipo',
            field=models.CharField(choices=[('busca', 'Busca de Duplicatas'), ('busca_ip', 'Busca por IP'), ('detalhamento_ip', 'Detalhamento de IP'), ('cancelamento', 'Cancelamento Individual'), ('cancelamento_lote', 'Cancelamento em Lote'), ('analise_pedido', 'Análise de Pedido'), ('debug', 'Debug de Dados'), ('erro', 'Erro')], max_length=20),
        ),
    ]
