# Generated by Django 5.2 on 2025-08-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0006_alter_processamentolog_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentolog',
            name='tipo',
            field=models.CharField(choices=[('busca', 'Busca de Duplicatas'), ('busca_ip', 'Busca por IP'), ('detalhamento_ip', 'Detalhamento de IP'), ('cancelamento', 'Cancelamento Individual'), ('cancelamento_lote', 'Cancelamento em Lote'), ('analise_pedido', 'Análise de Pedido'), ('debug', 'Debug de Dados'), ('erro', 'Erro'), ('busca_ips_simples', 'Busca IPs Simples'), ('busca_ip_async', 'Busca IP Assíncrona'), ('busca_ip_async_v2', 'Busca IP Assíncrona v2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processamentolog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
