# Generated by Django 5.2 on 2025-08-20 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0007_alter_processamentolog_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Endereço IP que foi resolvido')),
                ('resolved_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que foi marcado como resolvido')),
                ('notes', models.TextField(blank=True, help_text='Observações opcionais sobre a resolução do IP')),
                ('total_orders_at_resolution', models.IntegerField(default=0, help_text='Número total de pedidos deste IP no momento da resolução')),
                ('unique_customers_at_resolution', models.IntegerField(default=0, help_text='Número de clientes únicos deste IP no momento da resolução')),
                ('config', models.ForeignKey(help_text='Configuração da loja à qual este IP pertence', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_ips', to='processamento.shopifyconfig')),
                ('resolved_by', models.ForeignKey(help_text='Usuário que marcou este IP como resolvido', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Resolvido',
                'verbose_name_plural': 'IPs Resolvidos',
                'ordering': ['-resolved_at'],
                'indexes': [models.Index(fields=['config', 'ip_address'], name='processamen_config__e1e2eb_idx'), models.Index(fields=['resolved_at'], name='processamen_resolve_590e69_idx'), models.Index(fields=['resolved_by'], name='processamen_resolve_7e9561_idx')],
                'unique_together': {('config', 'ip_address')},
            },
        ),
    ]
