# Generated by Django 5.2 on 2025-08-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0008_resolvedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret do webhook para validação HMAC (opcional, mas recomendado para segurança)', max_length=255),
        ),
    ]
