# Generated by Django 5.2 on 2025-10-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0009_shopifyconfig_webhook_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedip',
            name='client_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados completos dos clientes e pedidos salvos no momento da resolução'),
        ),
        migrations.CreateModel(
            name='ObservedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Endereço IP que está em observação')),
                ('observed_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que foi marcado como em observação')),
                ('notes', models.TextField(blank=True, help_text='Observações opcionais sobre o IP em observação')),
                ('total_orders_at_observation', models.IntegerField(default=0, help_text='Número total de pedidos deste IP no momento da observação')),
                ('unique_customers_at_observation', models.IntegerField(default=0, help_text='Número de clientes únicos deste IP no momento da observação')),
                ('client_data', models.JSONField(blank=True, default=dict, help_text='Dados completos dos clientes e pedidos salvos no momento da observação')),
                ('config', models.ForeignKey(help_text='Configuração da loja à qual este IP pertence', on_delete=django.db.models.deletion.CASCADE, related_name='observed_ips', to='processamento.shopifyconfig')),
                ('observed_by', models.ForeignKey(help_text='Usuário que marcou este IP como em observação', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP em Observação',
                'verbose_name_plural': 'IPs em Observação',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['config', 'ip_address'], name='processamen_config__64a180_idx'), models.Index(fields=['observed_at'], name='processamen_observe_76aac3_idx')],
                'unique_together': {('config', 'ip_address')},
            },
        ),
    ]
