# Generated by Django 5.2 on 2025-07-15 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMappingEcomhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_original', models.CharField(max_length=100, verbose_name='Status Original')),
                ('status_mapeado', models.CharField(max_length=50, verbose_name='Status Mapeado')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mapeamento de Status ECOMHUB',
                'verbose_name_plural': 'Mapeamentos de Status ECOMHUB',
                'unique_together': {('status_original',)},
            },
        ),
        migrations.CreateModel(
            name='AnaliseEcomhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Análise')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dados_efetividade', models.JSONField(blank=True, null=True, verbose_name='Dados de Efetividade por Loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Análise ECOMHUB',
                'verbose_name_plural': 'Análises ECOMHUB',
                'ordering': ['-atualizado_em'],
                'unique_together': {('nome', 'criado_por')},
            },
        ),
    ]
