# Generated by Django 5.2 on 2025-08-20 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoStatusTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_amarelo_padrao', models.IntegerField(default=168, verbose_name='Limite Amarelo Padrão (horas)')),
                ('limite_vermelho_padrao', models.IntegerField(default=336, verbose_name='Limite Vermelho Padrão (horas)')),
                ('limite_critico_padrao', models.IntegerField(default=504, verbose_name='Limite Crítico Padrão (horas)')),
                ('limite_amarelo_entrega', models.IntegerField(default=72, verbose_name='Limite Amarelo Entrega (horas)')),
                ('limite_vermelho_entrega', models.IntegerField(default=120, verbose_name='Limite Vermelho Entrega (horas)')),
                ('limite_critico_entrega', models.IntegerField(default=168, verbose_name='Limite Crítico Entrega (horas)')),
                ('intervalo_sincronizacao', models.IntegerField(default=6, verbose_name='Intervalo de Sincronização (horas)')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Status Tracking',
                'verbose_name_plural': 'Configurações Status Tracking',
            },
        ),
        migrations.CreateModel(
            name='PedidoStatusAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Pedido')),
                ('status_atual', models.CharField(max_length=50, verbose_name='Status Atual')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone do Cliente')),
                ('produto_nome', models.CharField(max_length=300, verbose_name='Nome do Produto')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data_criacao', models.DateTimeField(verbose_name='Data de Criação')),
                ('data_ultima_atualizacao', models.DateTimeField(verbose_name='Última Atualização')),
                ('shopify_order_number', models.CharField(max_length=100, verbose_name='Número do Pedido Shopify')),
                ('tracking_url', models.URLField(blank=True, verbose_name='URL de Rastreamento')),
                ('tempo_no_status_atual', models.IntegerField(default=0, verbose_name='Tempo no Status Atual (horas)')),
                ('nivel_alerta', models.CharField(choices=[('normal', 'Normal'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('critico', 'Crítico')], default='normal', max_length=20, verbose_name='Nível de Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pedido Status Atual',
                'verbose_name_plural': 'Pedidos Status Atual',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status_atual'], name='metricas_ec_status__19b748_idx'), models.Index(fields=['nivel_alerta'], name='metricas_ec_nivel_a_91fad5_idx'), models.Index(fields=['pais'], name='metricas_ec_pais_164685_idx'), models.Index(fields=['tempo_no_status_atual'], name='metricas_ec_tempo_n_cc3ae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=50, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('data_mudanca', models.DateTimeField(verbose_name='Data da Mudança')),
                ('tempo_no_status_anterior', models.IntegerField(default=0, verbose_name='Tempo no Status Anterior (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='metricas_ecomhub.pedidostatusatual', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Histórico de Status',
                'ordering': ['-data_mudanca'],
                'indexes': [models.Index(fields=['pedido', '-data_mudanca'], name='metricas_ec_pedido__2b1380_idx'), models.Index(fields=['status_novo'], name='metricas_ec_status__a04240_idx')],
            },
        ),
    ]
