# Generated by Django 5.2 on 2025-10-27 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0002_configuracaostatustracking_pedidostatusatual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomhubStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome descritivo da loja', max_length=255)),
                ('token', models.CharField(help_text='Token da API ECOMHUB', max_length=255, unique=True)),
                ('secret', models.CharField(help_text='Secret da API ECOMHUB', max_length=255)),
                ('country_id', models.IntegerField(blank=True, help_text='ID do país na API ECOMHUB', null=True)),
                ('country_name', models.CharField(blank=True, help_text='Nome do país', max_length=100)),
                ('store_id', models.CharField(blank=True, help_text='ID da loja retornado pela API', max_length=255)),
                ('myshopify_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se False, não sincroniza pedidos')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronização de pedidos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja ECOMHUB',
                'verbose_name_plural': 'Lojas ECOMHUB',
                'ordering': ['-created_at'],
            },
        ),
    ]
