# Generated by Django 5.2 on 2025-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0002_add_shopify_integration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cacheprodutoshopify',
            new_name='metricas_ec_loja_sh_eb3b6d_idx',
            old_name='metricas_ec_loja_sh_5a7b57_idx',
        ),
        migrations.AlterField(
            model_name='analiseecomhub',
            name='dados_efetividade',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados de Efetividade por Produto'),
        ),
    ]
