# Generated by Django 5.2 on 2025-10-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0003_ecomhubstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomhubAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('preparing_for_shipping', 'Preparando Envio'), ('ready_to_ship', 'Pronto para Envio'), ('shipped', 'Enviado'), ('with_courier', 'Com Transportadora'), ('out_for_delivery', 'Saiu para Entrega'), ('issue', 'Com Problemas')], help_text='Status do pedido', max_length=50, unique=True)),
                ('yellow_threshold_hours', models.FloatField(default=48, help_text='Atenção após X horas (padrão: 48h = 2 dias)')),
                ('red_threshold_hours', models.FloatField(default=120, help_text='Urgente após X horas (padrão: 120h = 5 dias)')),
                ('critical_threshold_hours', models.FloatField(default=168, help_text='Crítico após X horas (padrão: 168h = 7 dias)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alertas',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='EcomhubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, help_text='ID único do pedido na API ECOMHUB', max_length=255)),
                ('country_id', models.IntegerField(db_index=True)),
                ('country_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(help_text='Data original do pedido')),
                ('status', models.CharField(db_index=True, help_text='Status atual', max_length=50)),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('product_name', models.TextField(blank=True, help_text='Nome do(s) produto(s)')),
                ('cost_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_commission_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_courier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_courier_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_payment_method', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_warehouse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_warehouse_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_since', models.DateTimeField(help_text='Quando entrou no status atual')),
                ('time_in_status_hours', models.FloatField(default=0, help_text='Horas no status atual')),
                ('previous_status', models.CharField(blank=True, help_text='Status anterior', max_length=50)),
                ('alert_level', models.CharField(choices=[('normal', 'Normal'), ('yellow', 'Atenção'), ('red', 'Urgente'), ('critical', 'Crítico')], db_index=True, default='normal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='metricas_ecomhub.ecomhubstore')),
            ],
            options={
                'verbose_name': 'Pedido ECOMHUB',
                'verbose_name_plural': 'Pedidos ECOMHUB',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EcomhubStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(help_text='Status anterior', max_length=50)),
                ('status_to', models.CharField(help_text='Novo status', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Quando mudou')),
                ('duration_in_previous_status_hours', models.FloatField(help_text='Tempo que ficou no status anterior')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='metricas_ecomhub.ecomhuborder')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ecomhuborder',
            index=models.Index(fields=['order_id'], name='metricas_ec_order_i_4b2e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ecomhuborder',
            index=models.Index(fields=['status'], name='metricas_ec_status_9c8c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ecomhuborder',
            index=models.Index(fields=['country_id'], name='metricas_ec_country_f2bce7_idx'),
        ),
        migrations.AddIndex(
            model_name='ecomhuborder',
            index=models.Index(fields=['alert_level'], name='metricas_ec_alert_l_9dfb35_idx'),
        ),
        migrations.AddIndex(
            model_name='ecomhuborder',
            index=models.Index(fields=['-time_in_status_hours'], name='metricas_ec_time_in_ff1a97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ecomhuborder',
            unique_together={('order_id', 'store')},
        ),
        migrations.AddIndex(
            model_name='ecomhubstatushistory',
            index=models.Index(fields=['order', '-changed_at'], name='metricas_ec_order_i_ff02f1_idx'),
        ),
    ]
