# Generated by Django 5.2 on 2025-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0004_add_async_processing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processamentojob',
            new_name='metricas_ec_job_id_47c5ab_idx',
            old_name='metricas_ec_job_id_eb2a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='processamentojob',
            new_name='metricas_ec_status_6046e5_idx',
            old_name='metricas_ec_status_5a8c5b_idx',
        ),
        migrations.RenameIndex(
            model_name='processamentojob',
            new_name='metricas_ec_criado__6fb07e_idx',
            old_name='metricas_ec_criado__9f6a2b_idx',
        ),
    ]
