# Generated by Django 5.2 on 2025-10-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0004_ecomhubalertconfig_ecomhuborder_ecomhubstatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomhubUnknownStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, help_text='Status desconhecido encontrado na API', max_length=100, unique=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True, help_text='Primeira vez que foi detectado')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Última vez que apareceu')),
                ('occurrences_count', models.IntegerField(default=1, help_text='Quantidade de vezes que apareceu')),
                ('sample_order_id', models.CharField(blank=True, help_text='Exemplo de pedido com este status', max_length=255)),
                ('reviewed', models.BooleanField(default=False, help_text='Se já foi revisado pelo usuário')),
                ('is_active', models.BooleanField(blank=True, help_text='True=ativo, False=final, None=não revisado', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Quando foi revisado', null=True)),
            ],
            options={
                'verbose_name': 'Status Desconhecido',
                'verbose_name_plural': 'Status Desconhecidos',
                'db_table': 'ecomhub_unknown_statuses',
                'ordering': ['-last_seen'],
            },
        ),
    ]
