# Generated by Django 5.2 on 2025-10-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0005_ecomhubunknownstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomhubalertconfig',
            name='status',
            field=models.CharField(choices=[('processing', 'Processando'), ('preparing_for_shipping', 'Preparando Envio'), ('ready_to_ship', 'Pronto para Envio'), ('shipped', 'Enviado'), ('with_courier', 'Com Transportadora'), ('out_for_delivery', 'Saiu para Entrega'), ('returning', 'Em Devolução'), ('issue', 'Com Problemas')], help_text='Status do pedido', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EfetividadeAnaliseV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para identificar a análise', max_length=255, verbose_name='Nome da Análise')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada (opcional)', null=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('dados_brutos', models.JSONField(help_text='Response completa da API ECOMHUB', verbose_name='Dados Brutos')),
                ('dados_processados', models.JSONField(help_text='Dados calculados: visualizacao_otimizada, visualizacao_total, stats', verbose_name='Dados Processados')),
                ('estatisticas', models.JSONField(help_text='Métricas agregadas: total_produtos, efetividade_media, etc', verbose_name='Estatísticas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('store', models.ForeignKey(blank=True, help_text="Loja específica ou null para 'todas as lojas'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_v2', to='metricas_ecomhub.ecomhubstore', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Análise Efetividade V2',
                'verbose_name_plural': 'Análises Efetividade V2',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['store', '-criado_em'], name='metricas_ec_store_i_cce144_idx'), models.Index(fields=['criado_por', '-criado_em'], name='metricas_ec_criado__e46504_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='metricas_ec_data_in_3df914_idx')],
            },
        ),
    ]
