# Generated by Django 5.2 on 2025-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ecomhub', '0006_alter_ecomhubalertconfig_status_efetividadeanalisev2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomhubalertconfig',
            name='business_hours_only',
            field=models.BooleanField(default=True, help_text='Se True, conta apenas dias úteis (seg-sex). Se False, conta todos os dias.'),
        ),
    ]
