# Generated by Django 5.2 on 2025-09-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseN1Italia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Análise')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dados_processados', models.JSONField(blank=True, null=True, verbose_name='Dados do Relatório N1')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Análise N1 Itália',
                'verbose_name_plural': 'Análises N1 Itália',
                'ordering': ['-atualizado_em'],
                'unique_together': {('nome', 'criado_por')},
            },
        ),
    ]
