# Generated by Django 5.2 on 2025-09-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_n1italia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analisen1italia',
            unique_together=set(),
        ),
    ]
