# Generated by Django 5.2 on 2026-01-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Primeiro dia da semana (segunda-feira)', verbose_name='Data Inicio (Segunda)')),
                ('data_fim', models.DateField(help_text='Ultimo dia da semana (domingo)', verbose_name='Data Fim (Domingo)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Semana de Referencia',
                'verbose_name_plural': 'Semanas de Referencia',
                'ordering': ['-data_inicio'],
                'unique_together': {('data_inicio', 'data_fim')},
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_account_id', models.CharField(help_text='ID da conta do usuario no Jira', max_length=100, verbose_name='Account ID Jira')),
                ('jira_display_name', models.CharField(help_text='Nome de exibicao do usuario no Jira', max_length=200, verbose_name='Nome Jira')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos_semanais', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='planejamento_semanal.semanareferencia', verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Planejamento Semanal',
                'verbose_name_plural': 'Planejamentos Semanais',
                'ordering': ['-semana__data_inicio', 'jira_display_name'],
                'unique_together': {('usuario', 'semana', 'jira_account_id')},
            },
        ),
        migrations.CreateModel(
            name='ItemPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(help_text='Chave da issue no Jira (ex: CHEGOU-123)', max_length=50, verbose_name='Chave da Issue')),
                ('issue_summary', models.CharField(help_text='Resumo/titulo da issue', max_length=500, verbose_name='Resumo')),
                ('issue_status', models.CharField(help_text='Status atual da issue no Jira', max_length=100, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade')),
                ('concluido', models.BooleanField(default=False, help_text='Se o item foi concluido nesta semana', verbose_name='Concluido')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibicao do item', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planejamento_semanal.planejamentosemanal', verbose_name='Planejamento')),
            ],
            options={
                'verbose_name': 'Item de Planejamento',
                'verbose_name_plural': 'Itens de Planejamento',
                'ordering': ['ordem', '-prioridade', 'issue_key'],
                'unique_together': {('planejamento', 'issue_key')},
            },
        ),
    ]
