# Generated by Django 5.2 on 2026-01-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_semanal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplanejamento',
            name='is_rotina',
            field=models.BooleanField(default=False, help_text='Se o item e uma tarefa de rotina', verbose_name='E Rotina'),
        ),
        migrations.AddField(
            model_name='itemplanejamento',
            name='mais_de_uma_semana',
            field=models.BooleanField(default=False, help_text='Se o item levara mais de uma semana para ser concluido', verbose_name='Mais de uma semana'),
        ),
        migrations.AddField(
            model_name='itemplanejamento',
            name='tempo_estimado',
            field=models.CharField(choices=[('PP', 'PP - Ate 1h'), ('P', 'P - 1h a 4h'), ('M', 'M - 4h a 8h'), ('G', 'G - 8h a 24h'), ('GG', 'GG - Ate 40h')], default='M', help_text='Estimativa de tempo para conclusao', max_length=2, verbose_name='Tempo Estimado'),
        ),
        migrations.AlterField(
            model_name='semanareferencia',
            name='data_fim',
            field=models.DateField(help_text='Ultimo dia da semana (sabado)', verbose_name='Data Fim (Sabado)'),
        ),
        migrations.AlterField(
            model_name='semanareferencia',
            name='data_inicio',
            field=models.DateField(help_text='Primeiro dia da semana (domingo)', verbose_name='Data Inicio (Domingo)'),
        ),
    ]
