# Generated by Django 5.2 on 2026-01-16 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_semanal', '0002_add_tempo_estimado_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Conteudo do aviso importante', verbose_name='Texto do Aviso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibicao do aviso', verbose_name='Ordem')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Aviso Importante',
                'verbose_name_plural': 'Avisos Importantes',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
