# Generated by Django 5.2 on 2025-10-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: INTRODUÇÃO, GESTÃO DE CUSTOS', max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Gerado automaticamente a partir do nome', unique=True, verbose_name='Slug')),
                ('ordem', models.IntegerField(default=0, help_text='Categorias com menor número aparecem primeiro', verbose_name='Ordem de Exibição')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (opcional, ex: fa-book, lucide-play-circle)', max_length=50, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, help_text='Categorias inativas não aparecem no site', verbose_name='Categoria Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria de Aula',
                'verbose_name_plural': 'Categorias de Aulas',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['ordem'], name='tutoriais_c_ordem_60404f_idx'), models.Index(fields=['ativo'], name='tutoriais_c_ativo_49ad7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Aula 1: Configurações Iniciais', max_length=200, verbose_name='Título da Aula')),
                ('slug', models.SlugField(help_text='Gerado automaticamente a partir do título', unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(help_text='Texto explicativo que aparece abaixo do vídeo', verbose_name='Descrição')),
                ('video_url', models.URLField(help_text='URL do YouTube no formato embed (ex: https://www.youtube.com/embed/VIDEO_ID)', verbose_name='URL do Vídeo')),
                ('ordem', models.IntegerField(default=0, help_text='Aulas com menor número aparecem primeiro dentro da categoria', verbose_name='Ordem na Categoria')),
                ('duracao', models.CharField(blank=True, help_text='Ex: 10:30 (opcional)', max_length=20, verbose_name='Duração')),
                ('ativo', models.BooleanField(default=True, help_text='Aulas inativas não aparecem no site', verbose_name='Aula Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='tutoriais.categoriaaula', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['categoria__ordem', 'ordem', 'titulo'],
                'indexes': [models.Index(fields=['categoria', 'ordem'], name='tutoriais_a_categor_7fc394_idx'), models.Index(fields=['ativo'], name='tutoriais_a_ativo_68d497_idx'), models.Index(fields=['slug'], name='tutoriais_a_slug_4f8e4e_idx')],
            },
        ),
    ]
