# Generated by Django 5.2 on 2025-10-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do YouTube (opcional, ex: https://www.youtube.com/watch?v=VIDEO_ID)', verbose_name='URL do Vídeo'),
        ),
    ]
