# Generated by Django 5.2 on 2025-07-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novelties', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='noveltyexecution',
            new_name='novelties_n_executi_f95b11_idx',
            old_name='novelties_n_executi_b8b2c4_idx',
        ),
        migrations.RenameIndex(
            model_name='noveltyexecution',
            new_name='novelties_n_country_c1b8f6_idx',
            old_name='novelties_n_country_8c5f42_idx',
        ),
        migrations.RenameIndex(
            model_name='noveltyexecution',
            new_name='novelties_n_status_048f9b_idx',
            old_name='novelties_n_status_9a4b21_idx',
        ),
    ]
