# Generated by Django 5.2 on 2025-07-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_dropi', '0002_add_dropi_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisedropi',
            options={'ordering': ['-atualizado_em'], 'verbose_name': 'Análise Dropi', 'verbose_name_plural': 'Análises Dropi'},
        ),
    ]
