# Generated by Django 5.2 on 2025-11-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Organização')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('plano', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('limite_membros', models.IntegerField(default=5, verbose_name='Limite de Membros')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['slug'], name='core_organi_slug_517c11_idx'), models.Index(fields=['ativo'], name='core_organi_ativo_a6b465_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner (Dono)'), ('admin', 'Admin (Administrador)'), ('member', 'Member (Membro)')], default='member', max_length=10, verbose_name='Função')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.organization', verbose_name='Organização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro da Organização',
                'verbose_name_plural': 'Membros das Organizações',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('agenda', 'Agenda da Empresa'), ('mapa', 'Mapa de Atuação'), ('ia_projetos', 'IA - Projetos'), ('ia_logs', 'IA - Logs de Erros'), ('ia_openai', 'IA - OpenAI Analytics'), ('ecomhub_efetividade', 'ECOMHUB - Análise de Efetividade'), ('ecomhub_efetividade_v2', 'ECOMHUB - Análise Avançada V2'), ('ecomhub_status', 'ECOMHUB - Status Tracking'), ('ecomhub_config', 'ECOMHUB - Configurações'), ('n1_efetividade', 'N1 - Efetividade'), ('primecod_efetividade', 'PRIMECOD - Efetividade'), ('dropi_efetividade', 'DROPI - Efetividade'), ('dropi_novelties', 'DROPI - Novelties'), ('shopify_estoque', 'Controle de Estoque'), ('shopify_processamento', 'Pedidos Duplicados'), ('shopify_detector_ip', 'Detector de IP'), ('facebook_engajamento', 'Facebook - Engajamento'), ('nicochat', 'Nicochat')], max_length=50, verbose_name='Módulo')),
                ('concedido_em', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos', to='core.organizationmember', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulos',
                'ordering': ['member', 'module_key'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Convidado')),
                ('role', models.CharField(choices=[('owner', 'Owner (Dono)'), ('admin', 'Admin (Administrador)'), ('member', 'Member (Membro)')], default='member', max_length=10, verbose_name='Função')),
                ('codigo', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Código')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Status')),
                ('aceito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to=settings.AUTH_USER_MODEL, verbose_name='Aceito por')),
                ('convidado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_criados', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Convite de Organização',
                'verbose_name_plural': 'Convites de Organização',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['codigo'], name='core_organi_codigo_dc88e7_idx'), models.Index(fields=['email', 'status'], name='core_organi_email_b09687_idx'), models.Index(fields=['organization', 'status'], name='core_organi_organiz_b16aa0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='core_organi_organiz_3e713d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['role'], name='core_organi_role_cb87bf_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['ativo'], name='core_organi_ativo_d5aca6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='usermodulepermission',
            index=models.Index(fields=['member', 'module_key'], name='core_usermo_member__f158bb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulepermission',
            index=models.Index(fields=['ativo'], name='core_usermo_ativo_b66bb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermodulepermission',
            unique_together={('member', 'module_key')},
        ),
    ]
