# Generated by Django 5.2 on 2025-04-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Um nome descritivo para o calendário (Ex: Marketing, Feriados).', max_length=100, verbose_name='Nome do Calendário')),
                ('google_calendar_id', models.CharField(help_text='O ID/Email do Google Calendar a ser incorporado.', max_length=255, unique=True, verbose_name='ID do Calendário Google (Email)')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Calendário Gerenciado',
                'verbose_name_plural': 'Calendários Gerenciados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Um nome curto e descritivo para o estilo (ex: 'Anúncio Google Ads', 'Desenho Infantil').", max_length=100, verbose_name='Nome do Estilo')),
                ('instructions', models.TextField(help_text='O texto/prompt base que será adicionado ANTES do prompt do usuário ao gerar imagens com este estilo.', verbose_name='Instruções do Estilo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_styles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estilo de Imagem',
                'verbose_name_plural': 'Estilos de Imagem',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
