# Generated by Django 5.2 on 2025-04-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedcalendar',
            options={'ordering': ['name'], 'verbose_name': 'Calendário Gerenciado (Iframe)', 'verbose_name_plural': 'Calendários Gerenciados (Iframe)'},
        ),
        migrations.RemoveField(
            model_name='managedcalendar',
            name='google_calendar_id',
        ),
        migrations.AddField(
            model_name='managedcalendar',
            name='iframe_code',
            field=models.TextField(blank=True, help_text='Cole aqui o código iframe completo obtido do Google Calendar.', null=True, unique=True, verbose_name='Código Iframe do Google Calendar'),
        ),
        migrations.DeleteModel(
            name='ImageStyle',
        ),
    ]
