# Generated by Django 5.2 on 2025-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_modulos_permitidos_to_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
