# Generated by Django 5.2 on 2025-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_modulos_permitidos_to_invite'),
    ]

    operations = [
        # Adicionar campo status com default='approved'
        # Isso garante que todas as organizações existentes sejam aprovadas automaticamente
        # Novas organizações usarão default='pending' definido no models.py
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')],
                default='approved',
                max_length=20,
                verbose_name='Status'
            ),
        ),
    ]
