# Generated by Django 5.2 on 2025-04-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagestyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeCODApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='Token da API')),
                ('base_url', models.URLField(default='https://api.primecod.app/api', verbose_name='URL Base')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração da API Prime COD',
                'verbose_name_plural': 'Configurações da API Prime COD',
            },
        ),
        migrations.CreateModel(
            name='PrimeCODProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU do Produto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('country_code', models.CharField(max_length=2, verbose_name='Código do País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto Prime COD',
                'verbose_name_plural': 'Produtos Prime COD',
                'unique_together': {('sku', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='PrimeCODOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Referência')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('pending', 'Pendente'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('returned', 'Devolvido'), ('wrong', 'Incorreto'), ('no_answer', 'Sem Resposta'), ('packed', 'Embalado'), ('confirmed', 'Confirmado'), ('duplicate', 'Duplicado')], max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('order_date', models.DateTimeField()),
                ('shipping_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.primecodproduct')),
            ],
            options={
                'verbose_name': 'Pedido Prime COD',
                'verbose_name_plural': 'Pedidos Prime COD',
            },
        ),
    ]
