# Generated by Django 5.2 on 2025-11-12 19:00

from django.db import migrations
from django.db.models import Q


def fix_existing_organizations_status(apps, schema_editor):
    """
    HOTFIX: Marca todas as organizações existentes como 'approved'.

    Problema: Organizações criadas ANTES da feature de aprovação podem estar
    sem status='approved', causando 404 nos endpoints porque get_queryset()
    filtra apenas organizações aprovadas.

    Solução: Atualizar organizações pending ou NULL para status='approved'.
    NÃO atualizar organizações rejected!
    """
    Organization = apps.get_model('core', 'Organization')

    # Buscar apenas organizações pending ou NULL (NÃO rejected!)
    organizacoes_para_aprovar = Organization.objects.filter(
        Q(status='pending') | Q(status__isnull=True) | Q(status='')
    )
    not_approved = organizacoes_para_aprovar.count()

    if not_approved > 0:
        # Atualizar apenas pending/NULL para 'approved'
        updated = organizacoes_para_aprovar.update(status='approved')
        print(f"HOTFIX: {updated} organizacao(oes) marcada(s) como 'approved'")
    else:
        print("Todas as organizacoes ja estao aprovadas")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_status'),
    ]

    operations = [
        migrations.RunPython(
            fix_existing_organizations_status,
            reverse_code=migrations.RunPython.noop
        ),
    ]
