# Generated by Django 5.2 on 2025-11-12 19:00

from django.db import migrations


def fix_existing_organizations_status(apps, schema_editor):
    """
    HOTFIX: Marca todas as organizações existentes como 'approved'.
    
    Problema: Organizações criadas ANTES da feature de aprovação podem estar
    sem status='approved', causando 404 nos endpoints porque get_queryset()
    filtra apenas organizações aprovadas.
    
    Solução: Atualizar TODAS as organizações para status='approved'.
    """
    Organization = apps.get_model('core', 'Organization')
    
    # Contar organizações que não estão aprovadas
    not_approved = Organization.objects.exclude(status='approved').count()
    
    if not_approved > 0:
        # Atualizar todas para 'approved'
        updated = Organization.objects.exclude(status='approved').update(status='approved')
        print(f"✅ HOTFIX: {updated} organização(ões) marcada(s) como 'approved'")
    else:
        print("ℹ️ Todas as organizações já estão aprovadas")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_status'),
    ]

    operations = [
        migrations.RunPython(
            fix_existing_organizations_status,
            reverse_code=migrations.RunPython.noop
        ),
    ]
