# Generated by Django 5.2 on 2025-11-14 14:25

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def fix_organizations_status(apps, schema_editor):
    """
    Garante que todas organizações ativas têm status='approved'.

    Contexto: Antes de adicionar filtro organization__status='approved' no código,
    precisamos garantir que organizações existentes estão com status correto.

    CRÍTICO: Esta migration evita loop infinito que acontece quando usuários
    ficam sem organizações aprovadas.
    """
    Organization = apps.get_model('core', 'Organization')

    # Buscar organizações que precisam de correção
    # APENAS pending - NÃO rejected!
    organizacoes_sem_aprovacao = Organization.objects.filter(
        ativo=True,
        status='pending'
    )

    total = organizacoes_sem_aprovacao.count()

    if total > 0:
        logger.info(f"Corrigindo {total} organizacoes ativas sem status 'approved'")

        # Listar o que será corrigido ANTES de atualizar
        for org in organizacoes_sem_aprovacao:
            logger.info(f"  {org.nome} (ID: {org.id}) -> status atual: {org.status or 'NULL'}")

        # Atualizar para approved
        count = organizacoes_sem_aprovacao.update(status='approved')
        logger.info(f"{count} organizacoes corrigidas para status='approved'!")

    else:
        logger.info("Todas as organizacoes ativas ja estao com status='approved'")


def reverse_fix(apps, schema_editor):
    """
    Reverso: não fazer nada (manter os dados corretos)

    Não podemos reverter porque não sabemos qual era o status anterior.
    A migration serve para CORRIGIR dados inconsistentes.
    """
    logger.info("Reverso da migration: nenhuma acao (dados permanecem como estao)")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_existing_organizations_status'),
    ]

    operations = [
        migrations.RunPython(fix_organizations_status, reverse_fix),
    ]
