# Generated by Django 5.2 on 2025-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_primecodapiconfig_primecodproduct_primecodorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primecodproduct',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='SKU do Produto'),
        ),
    ]
