# Generated by Django 5.2 on 2025-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_organizations_status_for_approved_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='modulos_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de module_keys que serão atribuídos ao aceitar o convite', verbose_name='Módulos Permitidos'),
        ),
    ]
